// Code generated by ent, DO NOT EDIT.

package doctor

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the doctor type in the database.
	Label = "doctor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldPracticeID holds the string denoting the practice_id field in the database.
	FieldPracticeID = "practice_id"
	// EdgePractice holds the string denoting the practice edge name in mutations.
	EdgePractice = "practice"
	// EdgePatientLinks holds the string denoting the patient_links edge name in mutations.
	EdgePatientLinks = "patient_links"
	// EdgeApprovedPatientLinks holds the string denoting the approved_patient_links edge name in mutations.
	EdgeApprovedPatientLinks = "approved_patient_links"
	// EdgeEntryShares holds the string denoting the entry_shares edge name in mutations.
	EdgeEntryShares = "entry_shares"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgeCreatedAnalysisJobs holds the string denoting the created_analysis_jobs edge name in mutations.
	EdgeCreatedAnalysisJobs = "created_analysis_jobs"
	// Table holds the table name of the doctor in the database.
	Table = "doctors"
	// PracticeTable is the table that holds the practice relation/edge.
	PracticeTable = "doctors"
	// PracticeInverseTable is the table name for the Practice entity.
	// It exists in this package in order to avoid circular dependency with the "practice" package.
	PracticeInverseTable = "practices"
	// PracticeColumn is the table column denoting the practice relation/edge.
	PracticeColumn = "practice_id"
	// PatientLinksTable is the table that holds the patient_links relation/edge.
	PatientLinksTable = "doctor_patient_links"
	// PatientLinksInverseTable is the table name for the DoctorPatientLink entity.
	// It exists in this package in order to avoid circular dependency with the "doctorpatientlink" package.
	PatientLinksInverseTable = "doctor_patient_links"
	// PatientLinksColumn is the table column denoting the patient_links relation/edge.
	PatientLinksColumn = "doctor_id"
	// ApprovedPatientLinksTable is the table that holds the approved_patient_links relation/edge.
	ApprovedPatientLinksTable = "doctor_patient_links"
	// ApprovedPatientLinksInverseTable is the table name for the DoctorPatientLink entity.
	// It exists in this package in order to avoid circular dependency with the "doctorpatientlink" package.
	ApprovedPatientLinksInverseTable = "doctor_patient_links"
	// ApprovedPatientLinksColumn is the table column denoting the approved_patient_links relation/edge.
	ApprovedPatientLinksColumn = "approved_by_doctor_id"
	// EntrySharesTable is the table that holds the entry_shares relation/edge.
	EntrySharesTable = "entry_shares"
	// EntrySharesInverseTable is the table name for the EntryShare entity.
	// It exists in this package in order to avoid circular dependency with the "entryshare" package.
	EntrySharesInverseTable = "entry_shares"
	// EntrySharesColumn is the table column denoting the entry_shares relation/edge.
	EntrySharesColumn = "shared_with_doctor_id"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "comments"
	// CommentsInverseTable is the table name for the Comment entity.
	// It exists in this package in order to avoid circular dependency with the "comment" package.
	CommentsInverseTable = "comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "author_doctor_id"
	// CreatedAnalysisJobsTable is the table that holds the created_analysis_jobs relation/edge.
	CreatedAnalysisJobsTable = "analysis_jobs"
	// CreatedAnalysisJobsInverseTable is the table name for the AnalysisJob entity.
	// It exists in this package in order to avoid circular dependency with the "analysisjob" package.
	CreatedAnalysisJobsInverseTable = "analysis_jobs"
	// CreatedAnalysisJobsColumn is the table column denoting the created_analysis_jobs relation/edge.
	CreatedAnalysisJobsColumn = "created_by_doctor_id"
)

// Columns holds all SQL columns for doctor fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEmail,
	FieldDisplayName,
	FieldRole,
	FieldPracticeID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Role defines the type for the "role" enum field.
type Role string

// RoleOwner is the default value of the Role enum.
const DefaultRole = RoleOwner

// Role values.
const (
	RoleOwner Role = "Owner"
	RoleStaff Role = "Staff"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleOwner, RoleStaff:
		return nil
	default:
		return fmt.Errorf("doctor: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the Doctor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByPracticeID orders the results by the practice_id field.
func ByPracticeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPracticeID, opts...).ToFunc()
}

// ByPracticeField orders the results by practice field.
func ByPracticeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPracticeStep(), sql.OrderByField(field, opts...))
	}
}

// ByPatientLinksCount orders the results by patient_links count.
func ByPatientLinksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPatientLinksStep(), opts...)
	}
}

// ByPatientLinks orders the results by patient_links terms.
func ByPatientLinks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPatientLinksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByApprovedPatientLinksCount orders the results by approved_patient_links count.
func ByApprovedPatientLinksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newApprovedPatientLinksStep(), opts...)
	}
}

// ByApprovedPatientLinks orders the results by approved_patient_links terms.
func ByApprovedPatientLinks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newApprovedPatientLinksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEntrySharesCount orders the results by entry_shares count.
func ByEntrySharesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEntrySharesStep(), opts...)
	}
}

// ByEntryShares orders the results by entry_shares terms.
func ByEntryShares(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntrySharesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCommentsCount orders the results by comments count.
func ByCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommentsStep(), opts...)
	}
}

// ByComments orders the results by comments terms.
func ByComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCreatedAnalysisJobsCount orders the results by created_analysis_jobs count.
func ByCreatedAnalysisJobsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCreatedAnalysisJobsStep(), opts...)
	}
}

// ByCreatedAnalysisJobs orders the results by created_analysis_jobs terms.
func ByCreatedAnalysisJobs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedAnalysisJobsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPracticeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PracticeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PracticeTable, PracticeColumn),
	)
}
func newPatientLinksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PatientLinksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PatientLinksTable, PatientLinksColumn),
	)
}
func newApprovedPatientLinksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ApprovedPatientLinksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ApprovedPatientLinksTable, ApprovedPatientLinksColumn),
	)
}
func newEntrySharesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntrySharesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EntrySharesTable, EntrySharesColumn),
	)
}
func newCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
	)
}
func newCreatedAnalysisJobsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedAnalysisJobsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CreatedAnalysisJobsTable, CreatedAnalysisJobsColumn),
	)
}
