// Code generated by ent, DO NOT EDIT.

package doctor

import (
	"backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldUpdatedAt, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldEmail, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldDisplayName, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldPasswordHash, v))
}

// PracticeID applies equality check predicate on the "practice_id" field. It's identical to PracticeIDEQ.
func PracticeID(v uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldPracticeID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Doctor {
	return predicate.Doctor(sql.FieldLTE(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Doctor {
	return predicate.Doctor(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Doctor {
	return predicate.Doctor(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldContainsFold(FieldEmail, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Doctor {
	return predicate.Doctor(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Doctor {
	return predicate.Doctor(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldContainsFold(FieldDisplayName, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.Doctor {
	return predicate.Doctor(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.Doctor {
	return predicate.Doctor(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.Doctor {
	return predicate.Doctor(sql.FieldContainsFold(FieldPasswordHash, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.Doctor {
	return predicate.Doctor(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.Doctor {
	return predicate.Doctor(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.Doctor {
	return predicate.Doctor(sql.FieldNotIn(FieldRole, vs...))
}

// PracticeIDEQ applies the EQ predicate on the "practice_id" field.
func PracticeIDEQ(v uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldEQ(FieldPracticeID, v))
}

// PracticeIDNEQ applies the NEQ predicate on the "practice_id" field.
func PracticeIDNEQ(v uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldNEQ(FieldPracticeID, v))
}

// PracticeIDIn applies the In predicate on the "practice_id" field.
func PracticeIDIn(vs ...uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldIn(FieldPracticeID, vs...))
}

// PracticeIDNotIn applies the NotIn predicate on the "practice_id" field.
func PracticeIDNotIn(vs ...uuid.UUID) predicate.Doctor {
	return predicate.Doctor(sql.FieldNotIn(FieldPracticeID, vs...))
}

// PracticeIDIsNil applies the IsNil predicate on the "practice_id" field.
func PracticeIDIsNil() predicate.Doctor {
	return predicate.Doctor(sql.FieldIsNull(FieldPracticeID))
}

// PracticeIDNotNil applies the NotNil predicate on the "practice_id" field.
func PracticeIDNotNil() predicate.Doctor {
	return predicate.Doctor(sql.FieldNotNull(FieldPracticeID))
}

// HasPractice applies the HasEdge predicate on the "practice" edge.
func HasPractice() predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PracticeTable, PracticeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPracticeWith applies the HasEdge predicate on the "practice" edge with a given conditions (other predicates).
func HasPracticeWith(preds ...predicate.Practice) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := newPracticeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPatientLinks applies the HasEdge predicate on the "patient_links" edge.
func HasPatientLinks() predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PatientLinksTable, PatientLinksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPatientLinksWith applies the HasEdge predicate on the "patient_links" edge with a given conditions (other predicates).
func HasPatientLinksWith(preds ...predicate.DoctorPatientLink) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := newPatientLinksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApprovedPatientLinks applies the HasEdge predicate on the "approved_patient_links" edge.
func HasApprovedPatientLinks() predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ApprovedPatientLinksTable, ApprovedPatientLinksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApprovedPatientLinksWith applies the HasEdge predicate on the "approved_patient_links" edge with a given conditions (other predicates).
func HasApprovedPatientLinksWith(preds ...predicate.DoctorPatientLink) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := newApprovedPatientLinksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntryShares applies the HasEdge predicate on the "entry_shares" edge.
func HasEntryShares() predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EntrySharesTable, EntrySharesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntrySharesWith applies the HasEdge predicate on the "entry_shares" edge with a given conditions (other predicates).
func HasEntrySharesWith(preds ...predicate.EntryShare) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := newEntrySharesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasComments applies the HasEdge predicate on the "comments" edge.
func HasComments() predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentsWith applies the HasEdge predicate on the "comments" edge with a given conditions (other predicates).
func HasCommentsWith(preds ...predicate.Comment) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := newCommentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreatedAnalysisJobs applies the HasEdge predicate on the "created_analysis_jobs" edge.
func HasCreatedAnalysisJobs() predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CreatedAnalysisJobsTable, CreatedAnalysisJobsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedAnalysisJobsWith applies the HasEdge predicate on the "created_analysis_jobs" edge with a given conditions (other predicates).
func HasCreatedAnalysisJobsWith(preds ...predicate.AnalysisJob) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := newCreatedAnalysisJobsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Doctor) predicate.Doctor {
	return predicate.Doctor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Doctor) predicate.Doctor {
	return predicate.Doctor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Doctor) predicate.Doctor {
	return predicate.Doctor(sql.NotPredicates(p))
}
