// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnalysisJobsColumns holds the columns for the "analysis_jobs" table.
	AnalysisJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "object_key", Type: field.TypeString},
		{Name: "kind", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"Queued", "Running", "Done", "Failed"}, Default: "Queued"},
		{Name: "progress", Type: field.TypeInt, Nullable: true},
		{Name: "result", Type: field.TypeJSON, Nullable: true},
		{Name: "metrics", Type: field.TypeJSON, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_by_doctor_id", Type: field.TypeUUID},
		{Name: "entry_id", Type: field.TypeUUID, Nullable: true},
		{Name: "patient_id", Type: field.TypeUUID},
	}
	// AnalysisJobsTable holds the schema information for the "analysis_jobs" table.
	AnalysisJobsTable = &schema.Table{
		Name:       "analysis_jobs",
		Columns:    AnalysisJobsColumns,
		PrimaryKey: []*schema.Column{AnalysisJobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "analysis_jobs_doctors_created_analysis_jobs",
				Columns:    []*schema.Column{AnalysisJobsColumns[12]},
				RefColumns: []*schema.Column{DoctorsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "analysis_jobs_entries_analysis_jobs",
				Columns:    []*schema.Column{AnalysisJobsColumns[13]},
				RefColumns: []*schema.Column{EntriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "analysis_jobs_patients_analysis_jobs",
				Columns:    []*schema.Column{AnalysisJobsColumns[14]},
				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "analysisjob_patient_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AnalysisJobsColumns[14], AnalysisJobsColumns[1]},
			},
			{
				Name:    "analysisjob_status",
				Unique:  false,
				Columns: []*schema.Column{AnalysisJobsColumns[5]},
			},
			{
				Name:    "analysisjob_created_by_doctor_id",
				Unique:  false,
				Columns: []*schema.Column{AnalysisJobsColumns[12]},
			},
		},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "body", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "author_doctor_id", Type: field.TypeUUID},
		{Name: "entry_id", Type: field.TypeUUID},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_doctors_comments",
				Columns:    []*schema.Column{CommentsColumns[3]},
				RefColumns: []*schema.Column{DoctorsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "comments_entries_comments",
				Columns:    []*schema.Column{CommentsColumns[4]},
				RefColumns: []*schema.Column{EntriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "comment_entry_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[4], CommentsColumns[2]},
			},
			{
				Name:    "comment_author_doctor_id",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[3]},
			},
		},
	}
	// DoctorsColumns holds the columns for the "doctors" table.
	DoctorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"Owner", "Staff"}, Default: "Owner"},
		{Name: "practice_id", Type: field.TypeUUID, Nullable: true},
	}
	// DoctorsTable holds the schema information for the "doctors" table.
	DoctorsTable = &schema.Table{
		Name:       "doctors",
		Columns:    DoctorsColumns,
		PrimaryKey: []*schema.Column{DoctorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "doctors_practices_doctors",
				Columns:    []*schema.Column{DoctorsColumns[7]},
				RefColumns: []*schema.Column{PracticesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "doctor_email",
				Unique:  true,
				Columns: []*schema.Column{DoctorsColumns[3]},
			},
			{
				Name:    "doctor_practice_id",
				Unique:  false,
				Columns: []*schema.Column{DoctorsColumns[7]},
			},
		},
	}
	// DoctorPatientLinksColumns holds the columns for the "doctor_patient_links" table.
	DoctorPatientLinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"Pending", "Approved", "Denied", "Revoked"}, Default: "Pending"},
		{Name: "requested_at", Type: field.TypeTime},
		{Name: "approved_at", Type: field.TypeTime, Nullable: true},
		{Name: "doctor_id", Type: field.TypeUUID},
		{Name: "approved_by_doctor_id", Type: field.TypeUUID, Nullable: true},
		{Name: "patient_id", Type: field.TypeUUID},
	}
	// DoctorPatientLinksTable holds the schema information for the "doctor_patient_links" table.
	DoctorPatientLinksTable = &schema.Table{
		Name:       "doctor_patient_links",
		Columns:    DoctorPatientLinksColumns,
		PrimaryKey: []*schema.Column{DoctorPatientLinksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "doctor_patient_links_doctors_patient_links",
				Columns:    []*schema.Column{DoctorPatientLinksColumns[6]},
				RefColumns: []*schema.Column{DoctorsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "doctor_patient_links_doctors_approved_patient_links",
				Columns:    []*schema.Column{DoctorPatientLinksColumns[7]},
				RefColumns: []*schema.Column{DoctorsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "doctor_patient_links_patients_doctor_links",
				Columns:    []*schema.Column{DoctorPatientLinksColumns[8]},
				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "doctorpatientlink_doctor_id_patient_id",
				Unique:  true,
				Columns: []*schema.Column{DoctorPatientLinksColumns[6], DoctorPatientLinksColumns[8]},
			},
			{
				Name:    "doctorpatientlink_status",
				Unique:  false,
				Columns: []*schema.Column{DoctorPatientLinksColumns[3]},
			},
			{
				Name:    "doctorpatientlink_requested_at",
				Unique:  false,
				Columns: []*schema.Column{DoctorPatientLinksColumns[4]},
			},
		},
	}
	// EntriesColumns holds the columns for the "entries" table.
	EntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "happened_at", Type: field.TypeTime},
		{Name: "situation", Type: field.TypeString, Nullable: true},
		{Name: "emotions", Type: field.TypeJSON, Nullable: true},
		{Name: "triggers", Type: field.TypeJSON, Nullable: true},
		{Name: "techniques", Type: field.TypeJSON, Nullable: true},
		{Name: "stutter_frequency", Type: field.TypeInt, Nullable: true},
		{Name: "notes", Type: field.TypeString, Nullable: true},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "patient_id", Type: field.TypeUUID},
	}
	// EntriesTable holds the schema information for the "entries" table.
	EntriesTable = &schema.Table{
		Name:       "entries",
		Columns:    EntriesColumns,
		PrimaryKey: []*schema.Column{EntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "entries_patients_entries",
				Columns:    []*schema.Column{EntriesColumns[11]},
				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "entry_patient_id_happened_at",
				Unique:  false,
				Columns: []*schema.Column{EntriesColumns[11], EntriesColumns[3]},
			},
			{
				Name:    "entry_happened_at",
				Unique:  false,
				Columns: []*schema.Column{EntriesColumns[3]},
			},
		},
	}
	// EntrySharesColumns holds the columns for the "entry_shares" table.
	EntrySharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "shared_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "shared_with_doctor_id", Type: field.TypeUUID},
		{Name: "entry_id", Type: field.TypeUUID},
		{Name: "shared_by_patient_id", Type: field.TypeUUID},
	}
	// EntrySharesTable holds the schema information for the "entry_shares" table.
	EntrySharesTable = &schema.Table{
		Name:       "entry_shares",
		Columns:    EntrySharesColumns,
		PrimaryKey: []*schema.Column{EntrySharesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "entry_shares_doctors_entry_shares",
				Columns:    []*schema.Column{EntrySharesColumns[5]},
				RefColumns: []*schema.Column{DoctorsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "entry_shares_entries_shares",
				Columns:    []*schema.Column{EntrySharesColumns[6]},
				RefColumns: []*schema.Column{EntriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "entry_shares_patients_entry_shares",
				Columns:    []*schema.Column{EntrySharesColumns[7]},
				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "entryshare_entry_id_shared_with_doctor_id",
				Unique:  true,
				Columns: []*schema.Column{EntrySharesColumns[6], EntrySharesColumns[5]},
			},
			{
				Name:    "entryshare_shared_with_doctor_id",
				Unique:  false,
				Columns: []*schema.Column{EntrySharesColumns[5]},
			},
			{
				Name:    "entryshare_shared_by_patient_id",
				Unique:  false,
				Columns: []*schema.Column{EntrySharesColumns[7]},
			},
			{
				Name:    "entryshare_shared_at",
				Unique:  false,
				Columns: []*schema.Column{EntrySharesColumns[3]},
			},
		},
	}
	// PatientsColumns holds the columns for the "patients" table.
	PatientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "display_name", Type: field.TypeString},
		{Name: "birth_date", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"Active", "Inactive"}, Default: "Active"},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "patient_code", Type: field.TypeString, Nullable: true},
		{Name: "last_entry_at", Type: field.TypeTime, Nullable: true},
	}
	// PatientsTable holds the schema information for the "patients" table.
	PatientsTable = &schema.Table{
		Name:       "patients",
		Columns:    PatientsColumns,
		PrimaryKey: []*schema.Column{PatientsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "uq_patient_email",
				Unique:  true,
				Columns: []*schema.Column{PatientsColumns[6]},
			},
			{
				Name:    "uq_patient_code",
				Unique:  true,
				Columns: []*schema.Column{PatientsColumns[8]},
			},
			{
				Name:    "patient_status",
				Unique:  false,
				Columns: []*schema.Column{PatientsColumns[5]},
			},
		},
	}
	// PracticesColumns holds the columns for the "practices" table.
	PracticesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "address", Type: field.TypeString, Nullable: true},
	}
	// PracticesTable holds the schema information for the "practices" table.
	PracticesTable = &schema.Table{
		Name:       "practices",
		Columns:    PracticesColumns,
		PrimaryKey: []*schema.Column{PracticesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnalysisJobsTable,
		CommentsTable,
		DoctorsTable,
		DoctorPatientLinksTable,
		EntriesTable,
		EntrySharesTable,
		PatientsTable,
		PracticesTable,
	}
)

func init() {
	AnalysisJobsTable.ForeignKeys[0].RefTable = DoctorsTable
	AnalysisJobsTable.ForeignKeys[1].RefTable = EntriesTable
	AnalysisJobsTable.ForeignKeys[2].RefTable = PatientsTable
	CommentsTable.ForeignKeys[0].RefTable = DoctorsTable
	CommentsTable.ForeignKeys[1].RefTable = EntriesTable
	DoctorsTable.ForeignKeys[0].RefTable = PracticesTable
	DoctorPatientLinksTable.ForeignKeys[0].RefTable = DoctorsTable
	DoctorPatientLinksTable.ForeignKeys[1].RefTable = DoctorsTable
	DoctorPatientLinksTable.ForeignKeys[2].RefTable = PatientsTable
	EntriesTable.ForeignKeys[0].RefTable = PatientsTable
	EntrySharesTable.ForeignKeys[0].RefTable = DoctorsTable
	EntrySharesTable.ForeignKeys[1].RefTable = EntriesTable
	EntrySharesTable.ForeignKeys[2].RefTable = PatientsTable
}
