// Code generated by ent, DO NOT EDIT.

package entryshare

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the entryshare type in the database.
	Label = "entry_share"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEntryID holds the string denoting the entry_id field in the database.
	FieldEntryID = "entry_id"
	// FieldSharedByPatientID holds the string denoting the shared_by_patient_id field in the database.
	FieldSharedByPatientID = "shared_by_patient_id"
	// FieldSharedWithDoctorID holds the string denoting the shared_with_doctor_id field in the database.
	FieldSharedWithDoctorID = "shared_with_doctor_id"
	// FieldSharedAt holds the string denoting the shared_at field in the database.
	FieldSharedAt = "shared_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// EdgeEntry holds the string denoting the entry edge name in mutations.
	EdgeEntry = "entry"
	// EdgeSharedByPatient holds the string denoting the shared_by_patient edge name in mutations.
	EdgeSharedByPatient = "shared_by_patient"
	// EdgeSharedWithDoctor holds the string denoting the shared_with_doctor edge name in mutations.
	EdgeSharedWithDoctor = "shared_with_doctor"
	// Table holds the table name of the entryshare in the database.
	Table = "entry_shares"
	// EntryTable is the table that holds the entry relation/edge.
	EntryTable = "entry_shares"
	// EntryInverseTable is the table name for the Entry entity.
	// It exists in this package in order to avoid circular dependency with the "entry" package.
	EntryInverseTable = "entries"
	// EntryColumn is the table column denoting the entry relation/edge.
	EntryColumn = "entry_id"
	// SharedByPatientTable is the table that holds the shared_by_patient relation/edge.
	SharedByPatientTable = "entry_shares"
	// SharedByPatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	SharedByPatientInverseTable = "patients"
	// SharedByPatientColumn is the table column denoting the shared_by_patient relation/edge.
	SharedByPatientColumn = "shared_by_patient_id"
	// SharedWithDoctorTable is the table that holds the shared_with_doctor relation/edge.
	SharedWithDoctorTable = "entry_shares"
	// SharedWithDoctorInverseTable is the table name for the Doctor entity.
	// It exists in this package in order to avoid circular dependency with the "doctor" package.
	SharedWithDoctorInverseTable = "doctors"
	// SharedWithDoctorColumn is the table column denoting the shared_with_doctor relation/edge.
	SharedWithDoctorColumn = "shared_with_doctor_id"
)

// Columns holds all SQL columns for entryshare fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEntryID,
	FieldSharedByPatientID,
	FieldSharedWithDoctorID,
	FieldSharedAt,
	FieldRevokedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultSharedAt holds the default value on creation for the "shared_at" field.
	DefaultSharedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the EntryShare queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEntryID orders the results by the entry_id field.
func ByEntryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryID, opts...).ToFunc()
}

// BySharedByPatientID orders the results by the shared_by_patient_id field.
func BySharedByPatientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSharedByPatientID, opts...).ToFunc()
}

// BySharedWithDoctorID orders the results by the shared_with_doctor_id field.
func BySharedWithDoctorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSharedWithDoctorID, opts...).ToFunc()
}

// BySharedAt orders the results by the shared_at field.
func BySharedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSharedAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByEntryField orders the results by entry field.
func ByEntryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntryStep(), sql.OrderByField(field, opts...))
	}
}

// BySharedByPatientField orders the results by shared_by_patient field.
func BySharedByPatientField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSharedByPatientStep(), sql.OrderByField(field, opts...))
	}
}

// BySharedWithDoctorField orders the results by shared_with_doctor field.
func BySharedWithDoctorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSharedWithDoctorStep(), sql.OrderByField(field, opts...))
	}
}
func newEntryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntryTable, EntryColumn),
	)
}
func newSharedByPatientStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SharedByPatientInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SharedByPatientTable, SharedByPatientColumn),
	)
}
func newSharedWithDoctorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SharedWithDoctorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SharedWithDoctorTable, SharedWithDoctorColumn),
	)
}
