// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/analysisjob"
	"backend/ent/comment"
	"backend/ent/doctor"
	"backend/ent/doctorpatientlink"
	"backend/ent/entryshare"
	"backend/ent/pairingcode"
	"backend/ent/practice"
	"backend/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DoctorUpdate is the builder for updating Doctor entities.
type DoctorUpdate struct {
	config
	hooks    []Hook
	mutation *DoctorMutation
}

// Where appends a list predicates to the DoctorUpdate builder.
func (_u *DoctorUpdate) Where(ps ...predicate.Doctor) *DoctorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DoctorUpdate) SetUpdatedAt(v time.Time) *DoctorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *DoctorUpdate) SetEmail(v string) *DoctorUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *DoctorUpdate) SetNillableEmail(v *string) *DoctorUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *DoctorUpdate) SetDisplayName(v string) *DoctorUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *DoctorUpdate) SetNillableDisplayName(v *string) *DoctorUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *DoctorUpdate) SetPasswordHash(v string) *DoctorUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *DoctorUpdate) SetNillablePasswordHash(v *string) *DoctorUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *DoctorUpdate) SetRole(v doctor.Role) *DoctorUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *DoctorUpdate) SetNillableRole(v *doctor.Role) *DoctorUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetPracticeID sets the "practice_id" field.
func (_u *DoctorUpdate) SetPracticeID(v uuid.UUID) *DoctorUpdate {
	_u.mutation.SetPracticeID(v)
	return _u
}

// SetNillablePracticeID sets the "practice_id" field if the given value is not nil.
func (_u *DoctorUpdate) SetNillablePracticeID(v *uuid.UUID) *DoctorUpdate {
	if v != nil {
		_u.SetPracticeID(*v)
	}
	return _u
}

// ClearPracticeID clears the value of the "practice_id" field.
func (_u *DoctorUpdate) ClearPracticeID() *DoctorUpdate {
	_u.mutation.ClearPracticeID()
	return _u
}

// SetPractice sets the "practice" edge to the Practice entity.
func (_u *DoctorUpdate) SetPractice(v *Practice) *DoctorUpdate {
	return _u.SetPracticeID(v.ID)
}

// AddPatientLinkIDs adds the "patient_links" edge to the DoctorPatientLink entity by IDs.
func (_u *DoctorUpdate) AddPatientLinkIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.AddPatientLinkIDs(ids...)
	return _u
}

// AddPatientLinks adds the "patient_links" edges to the DoctorPatientLink entity.
func (_u *DoctorUpdate) AddPatientLinks(v ...*DoctorPatientLink) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPatientLinkIDs(ids...)
}

// AddPairingCodeIDs adds the "pairing_codes" edge to the PairingCode entity by IDs.
func (_u *DoctorUpdate) AddPairingCodeIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.AddPairingCodeIDs(ids...)
	return _u
}

// AddPairingCodes adds the "pairing_codes" edges to the PairingCode entity.
func (_u *DoctorUpdate) AddPairingCodes(v ...*PairingCode) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPairingCodeIDs(ids...)
}

// AddApprovedPatientLinkIDs adds the "approved_patient_links" edge to the DoctorPatientLink entity by IDs.
func (_u *DoctorUpdate) AddApprovedPatientLinkIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.AddApprovedPatientLinkIDs(ids...)
	return _u
}

// AddApprovedPatientLinks adds the "approved_patient_links" edges to the DoctorPatientLink entity.
func (_u *DoctorUpdate) AddApprovedPatientLinks(v ...*DoctorPatientLink) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddApprovedPatientLinkIDs(ids...)
}

// AddEntryShareIDs adds the "entry_shares" edge to the EntryShare entity by IDs.
func (_u *DoctorUpdate) AddEntryShareIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.AddEntryShareIDs(ids...)
	return _u
}

// AddEntryShares adds the "entry_shares" edges to the EntryShare entity.
func (_u *DoctorUpdate) AddEntryShares(v ...*EntryShare) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryShareIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *DoctorUpdate) AddCommentIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *DoctorUpdate) AddComments(v ...*Comment) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddCreatedAnalysisJobIDs adds the "created_analysis_jobs" edge to the AnalysisJob entity by IDs.
func (_u *DoctorUpdate) AddCreatedAnalysisJobIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.AddCreatedAnalysisJobIDs(ids...)
	return _u
}

// AddCreatedAnalysisJobs adds the "created_analysis_jobs" edges to the AnalysisJob entity.
func (_u *DoctorUpdate) AddCreatedAnalysisJobs(v ...*AnalysisJob) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreatedAnalysisJobIDs(ids...)
}

// Mutation returns the DoctorMutation object of the builder.
func (_u *DoctorUpdate) Mutation() *DoctorMutation {
	return _u.mutation
}

// ClearPractice clears the "practice" edge to the Practice entity.
func (_u *DoctorUpdate) ClearPractice() *DoctorUpdate {
	_u.mutation.ClearPractice()
	return _u
}

// ClearPatientLinks clears all "patient_links" edges to the DoctorPatientLink entity.
func (_u *DoctorUpdate) ClearPatientLinks() *DoctorUpdate {
	_u.mutation.ClearPatientLinks()
	return _u
}

// RemovePatientLinkIDs removes the "patient_links" edge to DoctorPatientLink entities by IDs.
func (_u *DoctorUpdate) RemovePatientLinkIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.RemovePatientLinkIDs(ids...)
	return _u
}

// RemovePatientLinks removes "patient_links" edges to DoctorPatientLink entities.
func (_u *DoctorUpdate) RemovePatientLinks(v ...*DoctorPatientLink) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePatientLinkIDs(ids...)
}

// ClearPairingCodes clears all "pairing_codes" edges to the PairingCode entity.
func (_u *DoctorUpdate) ClearPairingCodes() *DoctorUpdate {
	_u.mutation.ClearPairingCodes()
	return _u
}

// RemovePairingCodeIDs removes the "pairing_codes" edge to PairingCode entities by IDs.
func (_u *DoctorUpdate) RemovePairingCodeIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.RemovePairingCodeIDs(ids...)
	return _u
}

// RemovePairingCodes removes "pairing_codes" edges to PairingCode entities.
func (_u *DoctorUpdate) RemovePairingCodes(v ...*PairingCode) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePairingCodeIDs(ids...)
}

// ClearApprovedPatientLinks clears all "approved_patient_links" edges to the DoctorPatientLink entity.
func (_u *DoctorUpdate) ClearApprovedPatientLinks() *DoctorUpdate {
	_u.mutation.ClearApprovedPatientLinks()
	return _u
}

// RemoveApprovedPatientLinkIDs removes the "approved_patient_links" edge to DoctorPatientLink entities by IDs.
func (_u *DoctorUpdate) RemoveApprovedPatientLinkIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.RemoveApprovedPatientLinkIDs(ids...)
	return _u
}

// RemoveApprovedPatientLinks removes "approved_patient_links" edges to DoctorPatientLink entities.
func (_u *DoctorUpdate) RemoveApprovedPatientLinks(v ...*DoctorPatientLink) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveApprovedPatientLinkIDs(ids...)
}

// ClearEntryShares clears all "entry_shares" edges to the EntryShare entity.
func (_u *DoctorUpdate) ClearEntryShares() *DoctorUpdate {
	_u.mutation.ClearEntryShares()
	return _u
}

// RemoveEntryShareIDs removes the "entry_shares" edge to EntryShare entities by IDs.
func (_u *DoctorUpdate) RemoveEntryShareIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.RemoveEntryShareIDs(ids...)
	return _u
}

// RemoveEntryShares removes "entry_shares" edges to EntryShare entities.
func (_u *DoctorUpdate) RemoveEntryShares(v ...*EntryShare) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryShareIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *DoctorUpdate) ClearComments() *DoctorUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *DoctorUpdate) RemoveCommentIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *DoctorUpdate) RemoveComments(v ...*Comment) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearCreatedAnalysisJobs clears all "created_analysis_jobs" edges to the AnalysisJob entity.
func (_u *DoctorUpdate) ClearCreatedAnalysisJobs() *DoctorUpdate {
	_u.mutation.ClearCreatedAnalysisJobs()
	return _u
}

// RemoveCreatedAnalysisJobIDs removes the "created_analysis_jobs" edge to AnalysisJob entities by IDs.
func (_u *DoctorUpdate) RemoveCreatedAnalysisJobIDs(ids ...uuid.UUID) *DoctorUpdate {
	_u.mutation.RemoveCreatedAnalysisJobIDs(ids...)
	return _u
}

// RemoveCreatedAnalysisJobs removes "created_analysis_jobs" edges to AnalysisJob entities.
func (_u *DoctorUpdate) RemoveCreatedAnalysisJobs(v ...*AnalysisJob) *DoctorUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreatedAnalysisJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DoctorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DoctorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DoctorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DoctorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DoctorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := doctor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DoctorUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := doctor.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Doctor.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := doctor.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Doctor.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := doctor.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Doctor.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := doctor.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Doctor.role": %w`, err)}
		}
	}
	return nil
}

func (_u *DoctorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(doctor.Table, doctor.Columns, sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(doctor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(doctor.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(doctor.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(doctor.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(doctor.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.PracticeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctor.PracticeTable,
			Columns: []string{doctor.PracticeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(practice.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PracticeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctor.PracticeTable,
			Columns: []string{doctor.PracticeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(practice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PatientLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PatientLinksTable,
			Columns: []string{doctor.PatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPatientLinksIDs(); len(nodes) > 0 && !_u.mutation.PatientLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PatientLinksTable,
			Columns: []string{doctor.PatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatientLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PatientLinksTable,
			Columns: []string{doctor.PatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PairingCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PairingCodesTable,
			Columns: []string{doctor.PairingCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pairingcode.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPairingCodesIDs(); len(nodes) > 0 && !_u.mutation.PairingCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PairingCodesTable,
			Columns: []string{doctor.PairingCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pairingcode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PairingCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PairingCodesTable,
			Columns: []string{doctor.PairingCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pairingcode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ApprovedPatientLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.ApprovedPatientLinksTable,
			Columns: []string{doctor.ApprovedPatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedApprovedPatientLinksIDs(); len(nodes) > 0 && !_u.mutation.ApprovedPatientLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.ApprovedPatientLinksTable,
			Columns: []string{doctor.ApprovedPatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApprovedPatientLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.ApprovedPatientLinksTable,
			Columns: []string{doctor.ApprovedPatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntrySharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.EntrySharesTable,
			Columns: []string{doctor.EntrySharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntrySharesIDs(); len(nodes) > 0 && !_u.mutation.EntrySharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.EntrySharesTable,
			Columns: []string{doctor.EntrySharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntrySharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.EntrySharesTable,
			Columns: []string{doctor.EntrySharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CommentsTable,
			Columns: []string{doctor.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CommentsTable,
			Columns: []string{doctor.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CommentsTable,
			Columns: []string{doctor.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedAnalysisJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CreatedAnalysisJobsTable,
			Columns: []string{doctor.CreatedAnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreatedAnalysisJobsIDs(); len(nodes) > 0 && !_u.mutation.CreatedAnalysisJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CreatedAnalysisJobsTable,
			Columns: []string{doctor.CreatedAnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedAnalysisJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CreatedAnalysisJobsTable,
			Columns: []string{doctor.CreatedAnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{doctor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DoctorUpdateOne is the builder for updating a single Doctor entity.
type DoctorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DoctorMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DoctorUpdateOne) SetUpdatedAt(v time.Time) *DoctorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *DoctorUpdateOne) SetEmail(v string) *DoctorUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *DoctorUpdateOne) SetNillableEmail(v *string) *DoctorUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *DoctorUpdateOne) SetDisplayName(v string) *DoctorUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *DoctorUpdateOne) SetNillableDisplayName(v *string) *DoctorUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *DoctorUpdateOne) SetPasswordHash(v string) *DoctorUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *DoctorUpdateOne) SetNillablePasswordHash(v *string) *DoctorUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *DoctorUpdateOne) SetRole(v doctor.Role) *DoctorUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *DoctorUpdateOne) SetNillableRole(v *doctor.Role) *DoctorUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetPracticeID sets the "practice_id" field.
func (_u *DoctorUpdateOne) SetPracticeID(v uuid.UUID) *DoctorUpdateOne {
	_u.mutation.SetPracticeID(v)
	return _u
}

// SetNillablePracticeID sets the "practice_id" field if the given value is not nil.
func (_u *DoctorUpdateOne) SetNillablePracticeID(v *uuid.UUID) *DoctorUpdateOne {
	if v != nil {
		_u.SetPracticeID(*v)
	}
	return _u
}

// ClearPracticeID clears the value of the "practice_id" field.
func (_u *DoctorUpdateOne) ClearPracticeID() *DoctorUpdateOne {
	_u.mutation.ClearPracticeID()
	return _u
}

// SetPractice sets the "practice" edge to the Practice entity.
func (_u *DoctorUpdateOne) SetPractice(v *Practice) *DoctorUpdateOne {
	return _u.SetPracticeID(v.ID)
}

// AddPatientLinkIDs adds the "patient_links" edge to the DoctorPatientLink entity by IDs.
func (_u *DoctorUpdateOne) AddPatientLinkIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.AddPatientLinkIDs(ids...)
	return _u
}

// AddPatientLinks adds the "patient_links" edges to the DoctorPatientLink entity.
func (_u *DoctorUpdateOne) AddPatientLinks(v ...*DoctorPatientLink) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPatientLinkIDs(ids...)
}

// AddPairingCodeIDs adds the "pairing_codes" edge to the PairingCode entity by IDs.
func (_u *DoctorUpdateOne) AddPairingCodeIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.AddPairingCodeIDs(ids...)
	return _u
}

// AddPairingCodes adds the "pairing_codes" edges to the PairingCode entity.
func (_u *DoctorUpdateOne) AddPairingCodes(v ...*PairingCode) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPairingCodeIDs(ids...)
}

// AddApprovedPatientLinkIDs adds the "approved_patient_links" edge to the DoctorPatientLink entity by IDs.
func (_u *DoctorUpdateOne) AddApprovedPatientLinkIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.AddApprovedPatientLinkIDs(ids...)
	return _u
}

// AddApprovedPatientLinks adds the "approved_patient_links" edges to the DoctorPatientLink entity.
func (_u *DoctorUpdateOne) AddApprovedPatientLinks(v ...*DoctorPatientLink) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddApprovedPatientLinkIDs(ids...)
}

// AddEntryShareIDs adds the "entry_shares" edge to the EntryShare entity by IDs.
func (_u *DoctorUpdateOne) AddEntryShareIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.AddEntryShareIDs(ids...)
	return _u
}

// AddEntryShares adds the "entry_shares" edges to the EntryShare entity.
func (_u *DoctorUpdateOne) AddEntryShares(v ...*EntryShare) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryShareIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *DoctorUpdateOne) AddCommentIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *DoctorUpdateOne) AddComments(v ...*Comment) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddCreatedAnalysisJobIDs adds the "created_analysis_jobs" edge to the AnalysisJob entity by IDs.
func (_u *DoctorUpdateOne) AddCreatedAnalysisJobIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.AddCreatedAnalysisJobIDs(ids...)
	return _u
}

// AddCreatedAnalysisJobs adds the "created_analysis_jobs" edges to the AnalysisJob entity.
func (_u *DoctorUpdateOne) AddCreatedAnalysisJobs(v ...*AnalysisJob) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCreatedAnalysisJobIDs(ids...)
}

// Mutation returns the DoctorMutation object of the builder.
func (_u *DoctorUpdateOne) Mutation() *DoctorMutation {
	return _u.mutation
}

// ClearPractice clears the "practice" edge to the Practice entity.
func (_u *DoctorUpdateOne) ClearPractice() *DoctorUpdateOne {
	_u.mutation.ClearPractice()
	return _u
}

// ClearPatientLinks clears all "patient_links" edges to the DoctorPatientLink entity.
func (_u *DoctorUpdateOne) ClearPatientLinks() *DoctorUpdateOne {
	_u.mutation.ClearPatientLinks()
	return _u
}

// RemovePatientLinkIDs removes the "patient_links" edge to DoctorPatientLink entities by IDs.
func (_u *DoctorUpdateOne) RemovePatientLinkIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.RemovePatientLinkIDs(ids...)
	return _u
}

// RemovePatientLinks removes "patient_links" edges to DoctorPatientLink entities.
func (_u *DoctorUpdateOne) RemovePatientLinks(v ...*DoctorPatientLink) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePatientLinkIDs(ids...)
}

// ClearPairingCodes clears all "pairing_codes" edges to the PairingCode entity.
func (_u *DoctorUpdateOne) ClearPairingCodes() *DoctorUpdateOne {
	_u.mutation.ClearPairingCodes()
	return _u
}

// RemovePairingCodeIDs removes the "pairing_codes" edge to PairingCode entities by IDs.
func (_u *DoctorUpdateOne) RemovePairingCodeIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.RemovePairingCodeIDs(ids...)
	return _u
}

// RemovePairingCodes removes "pairing_codes" edges to PairingCode entities.
func (_u *DoctorUpdateOne) RemovePairingCodes(v ...*PairingCode) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePairingCodeIDs(ids...)
}

// ClearApprovedPatientLinks clears all "approved_patient_links" edges to the DoctorPatientLink entity.
func (_u *DoctorUpdateOne) ClearApprovedPatientLinks() *DoctorUpdateOne {
	_u.mutation.ClearApprovedPatientLinks()
	return _u
}

// RemoveApprovedPatientLinkIDs removes the "approved_patient_links" edge to DoctorPatientLink entities by IDs.
func (_u *DoctorUpdateOne) RemoveApprovedPatientLinkIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.RemoveApprovedPatientLinkIDs(ids...)
	return _u
}

// RemoveApprovedPatientLinks removes "approved_patient_links" edges to DoctorPatientLink entities.
func (_u *DoctorUpdateOne) RemoveApprovedPatientLinks(v ...*DoctorPatientLink) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveApprovedPatientLinkIDs(ids...)
}

// ClearEntryShares clears all "entry_shares" edges to the EntryShare entity.
func (_u *DoctorUpdateOne) ClearEntryShares() *DoctorUpdateOne {
	_u.mutation.ClearEntryShares()
	return _u
}

// RemoveEntryShareIDs removes the "entry_shares" edge to EntryShare entities by IDs.
func (_u *DoctorUpdateOne) RemoveEntryShareIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.RemoveEntryShareIDs(ids...)
	return _u
}

// RemoveEntryShares removes "entry_shares" edges to EntryShare entities.
func (_u *DoctorUpdateOne) RemoveEntryShares(v ...*EntryShare) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryShareIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *DoctorUpdateOne) ClearComments() *DoctorUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *DoctorUpdateOne) RemoveCommentIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *DoctorUpdateOne) RemoveComments(v ...*Comment) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearCreatedAnalysisJobs clears all "created_analysis_jobs" edges to the AnalysisJob entity.
func (_u *DoctorUpdateOne) ClearCreatedAnalysisJobs() *DoctorUpdateOne {
	_u.mutation.ClearCreatedAnalysisJobs()
	return _u
}

// RemoveCreatedAnalysisJobIDs removes the "created_analysis_jobs" edge to AnalysisJob entities by IDs.
func (_u *DoctorUpdateOne) RemoveCreatedAnalysisJobIDs(ids ...uuid.UUID) *DoctorUpdateOne {
	_u.mutation.RemoveCreatedAnalysisJobIDs(ids...)
	return _u
}

// RemoveCreatedAnalysisJobs removes "created_analysis_jobs" edges to AnalysisJob entities.
func (_u *DoctorUpdateOne) RemoveCreatedAnalysisJobs(v ...*AnalysisJob) *DoctorUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCreatedAnalysisJobIDs(ids...)
}

// Where appends a list predicates to the DoctorUpdate builder.
func (_u *DoctorUpdateOne) Where(ps ...predicate.Doctor) *DoctorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DoctorUpdateOne) Select(field string, fields ...string) *DoctorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Doctor entity.
func (_u *DoctorUpdateOne) Save(ctx context.Context) (*Doctor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DoctorUpdateOne) SaveX(ctx context.Context) *Doctor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DoctorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DoctorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DoctorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := doctor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DoctorUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := doctor.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Doctor.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := doctor.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Doctor.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := doctor.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Doctor.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := doctor.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Doctor.role": %w`, err)}
		}
	}
	return nil
}

func (_u *DoctorUpdateOne) sqlSave(ctx context.Context) (_node *Doctor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(doctor.Table, doctor.Columns, sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Doctor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, doctor.FieldID)
		for _, f := range fields {
			if !doctor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != doctor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(doctor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(doctor.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(doctor.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(doctor.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(doctor.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.PracticeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctor.PracticeTable,
			Columns: []string{doctor.PracticeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(practice.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PracticeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctor.PracticeTable,
			Columns: []string{doctor.PracticeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(practice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PatientLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PatientLinksTable,
			Columns: []string{doctor.PatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPatientLinksIDs(); len(nodes) > 0 && !_u.mutation.PatientLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PatientLinksTable,
			Columns: []string{doctor.PatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatientLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PatientLinksTable,
			Columns: []string{doctor.PatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PairingCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PairingCodesTable,
			Columns: []string{doctor.PairingCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pairingcode.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPairingCodesIDs(); len(nodes) > 0 && !_u.mutation.PairingCodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PairingCodesTable,
			Columns: []string{doctor.PairingCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pairingcode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PairingCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PairingCodesTable,
			Columns: []string{doctor.PairingCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pairingcode.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ApprovedPatientLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.ApprovedPatientLinksTable,
			Columns: []string{doctor.ApprovedPatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedApprovedPatientLinksIDs(); len(nodes) > 0 && !_u.mutation.ApprovedPatientLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.ApprovedPatientLinksTable,
			Columns: []string{doctor.ApprovedPatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApprovedPatientLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.ApprovedPatientLinksTable,
			Columns: []string{doctor.ApprovedPatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntrySharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.EntrySharesTable,
			Columns: []string{doctor.EntrySharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntrySharesIDs(); len(nodes) > 0 && !_u.mutation.EntrySharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.EntrySharesTable,
			Columns: []string{doctor.EntrySharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntrySharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.EntrySharesTable,
			Columns: []string{doctor.EntrySharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CommentsTable,
			Columns: []string{doctor.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CommentsTable,
			Columns: []string{doctor.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CommentsTable,
			Columns: []string{doctor.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedAnalysisJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CreatedAnalysisJobsTable,
			Columns: []string{doctor.CreatedAnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCreatedAnalysisJobsIDs(); len(nodes) > 0 && !_u.mutation.CreatedAnalysisJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CreatedAnalysisJobsTable,
			Columns: []string{doctor.CreatedAnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedAnalysisJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CreatedAnalysisJobsTable,
			Columns: []string{doctor.CreatedAnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Doctor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{doctor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
