// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/doctor"
	"backend/ent/doctorpatientlink"
	"backend/ent/patient"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DoctorPatientLinkCreate is the builder for creating a DoctorPatientLink entity.
type DoctorPatientLinkCreate struct {
	config
	mutation *DoctorPatientLinkMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DoctorPatientLinkCreate) SetCreatedAt(v time.Time) *DoctorPatientLinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DoctorPatientLinkCreate) SetNillableCreatedAt(v *time.Time) *DoctorPatientLinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DoctorPatientLinkCreate) SetUpdatedAt(v time.Time) *DoctorPatientLinkCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DoctorPatientLinkCreate) SetNillableUpdatedAt(v *time.Time) *DoctorPatientLinkCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDoctorID sets the "doctor_id" field.
func (_c *DoctorPatientLinkCreate) SetDoctorID(v uuid.UUID) *DoctorPatientLinkCreate {
	_c.mutation.SetDoctorID(v)
	return _c
}

// SetPatientID sets the "patient_id" field.
func (_c *DoctorPatientLinkCreate) SetPatientID(v uuid.UUID) *DoctorPatientLinkCreate {
	_c.mutation.SetPatientID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DoctorPatientLinkCreate) SetStatus(v doctorpatientlink.Status) *DoctorPatientLinkCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DoctorPatientLinkCreate) SetNillableStatus(v *doctorpatientlink.Status) *DoctorPatientLinkCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRequestedAt sets the "requested_at" field.
func (_c *DoctorPatientLinkCreate) SetRequestedAt(v time.Time) *DoctorPatientLinkCreate {
	_c.mutation.SetRequestedAt(v)
	return _c
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_c *DoctorPatientLinkCreate) SetNillableRequestedAt(v *time.Time) *DoctorPatientLinkCreate {
	if v != nil {
		_c.SetRequestedAt(*v)
	}
	return _c
}

// SetApprovedAt sets the "approved_at" field.
func (_c *DoctorPatientLinkCreate) SetApprovedAt(v time.Time) *DoctorPatientLinkCreate {
	_c.mutation.SetApprovedAt(v)
	return _c
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_c *DoctorPatientLinkCreate) SetNillableApprovedAt(v *time.Time) *DoctorPatientLinkCreate {
	if v != nil {
		_c.SetApprovedAt(*v)
	}
	return _c
}

// SetApprovedByDoctorID sets the "approved_by_doctor_id" field.
func (_c *DoctorPatientLinkCreate) SetApprovedByDoctorID(v uuid.UUID) *DoctorPatientLinkCreate {
	_c.mutation.SetApprovedByDoctorID(v)
	return _c
}

// SetNillableApprovedByDoctorID sets the "approved_by_doctor_id" field if the given value is not nil.
func (_c *DoctorPatientLinkCreate) SetNillableApprovedByDoctorID(v *uuid.UUID) *DoctorPatientLinkCreate {
	if v != nil {
		_c.SetApprovedByDoctorID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DoctorPatientLinkCreate) SetID(v uuid.UUID) *DoctorPatientLinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DoctorPatientLinkCreate) SetNillableID(v *uuid.UUID) *DoctorPatientLinkCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDoctor sets the "doctor" edge to the Doctor entity.
func (_c *DoctorPatientLinkCreate) SetDoctor(v *Doctor) *DoctorPatientLinkCreate {
	return _c.SetDoctorID(v.ID)
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_c *DoctorPatientLinkCreate) SetPatient(v *Patient) *DoctorPatientLinkCreate {
	return _c.SetPatientID(v.ID)
}

// SetApprovedByID sets the "approved_by" edge to the Doctor entity by ID.
func (_c *DoctorPatientLinkCreate) SetApprovedByID(id uuid.UUID) *DoctorPatientLinkCreate {
	_c.mutation.SetApprovedByID(id)
	return _c
}

// SetNillableApprovedByID sets the "approved_by" edge to the Doctor entity by ID if the given value is not nil.
func (_c *DoctorPatientLinkCreate) SetNillableApprovedByID(id *uuid.UUID) *DoctorPatientLinkCreate {
	if id != nil {
		_c = _c.SetApprovedByID(*id)
	}
	return _c
}

// SetApprovedBy sets the "approved_by" edge to the Doctor entity.
func (_c *DoctorPatientLinkCreate) SetApprovedBy(v *Doctor) *DoctorPatientLinkCreate {
	return _c.SetApprovedByID(v.ID)
}

// Mutation returns the DoctorPatientLinkMutation object of the builder.
func (_c *DoctorPatientLinkCreate) Mutation() *DoctorPatientLinkMutation {
	return _c.mutation
}

// Save creates the DoctorPatientLink in the database.
func (_c *DoctorPatientLinkCreate) Save(ctx context.Context) (*DoctorPatientLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DoctorPatientLinkCreate) SaveX(ctx context.Context) *DoctorPatientLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DoctorPatientLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DoctorPatientLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DoctorPatientLinkCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := doctorpatientlink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := doctorpatientlink.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := doctorpatientlink.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RequestedAt(); !ok {
		v := doctorpatientlink.DefaultRequestedAt()
		_c.mutation.SetRequestedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := doctorpatientlink.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DoctorPatientLinkCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DoctorPatientLink.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DoctorPatientLink.updated_at"`)}
	}
	if _, ok := _c.mutation.DoctorID(); !ok {
		return &ValidationError{Name: "doctor_id", err: errors.New(`ent: missing required field "DoctorPatientLink.doctor_id"`)}
	}
	if _, ok := _c.mutation.PatientID(); !ok {
		return &ValidationError{Name: "patient_id", err: errors.New(`ent: missing required field "DoctorPatientLink.patient_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DoctorPatientLink.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := doctorpatientlink.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DoctorPatientLink.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requested_at", err: errors.New(`ent: missing required field "DoctorPatientLink.requested_at"`)}
	}
	if len(_c.mutation.DoctorIDs()) == 0 {
		return &ValidationError{Name: "doctor", err: errors.New(`ent: missing required edge "DoctorPatientLink.doctor"`)}
	}
	if len(_c.mutation.PatientIDs()) == 0 {
		return &ValidationError{Name: "patient", err: errors.New(`ent: missing required edge "DoctorPatientLink.patient"`)}
	}
	return nil
}

func (_c *DoctorPatientLinkCreate) sqlSave(ctx context.Context) (*DoctorPatientLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DoctorPatientLinkCreate) createSpec() (*DoctorPatientLink, *sqlgraph.CreateSpec) {
	var (
		_node = &DoctorPatientLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(doctorpatientlink.Table, sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(doctorpatientlink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(doctorpatientlink.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(doctorpatientlink.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RequestedAt(); ok {
		_spec.SetField(doctorpatientlink.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	if value, ok := _c.mutation.ApprovedAt(); ok {
		_spec.SetField(doctorpatientlink.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = &value
	}
	if nodes := _c.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctorpatientlink.DoctorTable,
			Columns: []string{doctorpatientlink.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DoctorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctorpatientlink.PatientTable,
			Columns: []string{doctorpatientlink.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PatientID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ApprovedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctorpatientlink.ApprovedByTable,
			Columns: []string{doctorpatientlink.ApprovedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApprovedByDoctorID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DoctorPatientLinkCreateBulk is the builder for creating many DoctorPatientLink entities in bulk.
type DoctorPatientLinkCreateBulk struct {
	config
	err      error
	builders []*DoctorPatientLinkCreate
}

// Save creates the DoctorPatientLink entities in the database.
func (_c *DoctorPatientLinkCreateBulk) Save(ctx context.Context) ([]*DoctorPatientLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DoctorPatientLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DoctorPatientLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DoctorPatientLinkCreateBulk) SaveX(ctx context.Context) []*DoctorPatientLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DoctorPatientLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DoctorPatientLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
