// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/analysisjob"
	"backend/ent/comment"
	"backend/ent/doctor"
	"backend/ent/doctorpatientlink"
	"backend/ent/entryshare"
	"backend/ent/practice"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DoctorCreate is the builder for creating a Doctor entity.
type DoctorCreate struct {
	config
	mutation *DoctorMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *DoctorCreate) SetCreatedAt(v time.Time) *DoctorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DoctorCreate) SetNillableCreatedAt(v *time.Time) *DoctorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DoctorCreate) SetUpdatedAt(v time.Time) *DoctorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DoctorCreate) SetNillableUpdatedAt(v *time.Time) *DoctorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *DoctorCreate) SetEmail(v string) *DoctorCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *DoctorCreate) SetDisplayName(v string) *DoctorCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *DoctorCreate) SetRole(v doctor.Role) *DoctorCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *DoctorCreate) SetNillableRole(v *doctor.Role) *DoctorCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetPracticeID sets the "practice_id" field.
func (_c *DoctorCreate) SetPracticeID(v uuid.UUID) *DoctorCreate {
	_c.mutation.SetPracticeID(v)
	return _c
}

// SetNillablePracticeID sets the "practice_id" field if the given value is not nil.
func (_c *DoctorCreate) SetNillablePracticeID(v *uuid.UUID) *DoctorCreate {
	if v != nil {
		_c.SetPracticeID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DoctorCreate) SetID(v uuid.UUID) *DoctorCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DoctorCreate) SetNillableID(v *uuid.UUID) *DoctorCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPractice sets the "practice" edge to the Practice entity.
func (_c *DoctorCreate) SetPractice(v *Practice) *DoctorCreate {
	return _c.SetPracticeID(v.ID)
}

// AddPatientLinkIDs adds the "patient_links" edge to the DoctorPatientLink entity by IDs.
func (_c *DoctorCreate) AddPatientLinkIDs(ids ...uuid.UUID) *DoctorCreate {
	_c.mutation.AddPatientLinkIDs(ids...)
	return _c
}

// AddPatientLinks adds the "patient_links" edges to the DoctorPatientLink entity.
func (_c *DoctorCreate) AddPatientLinks(v ...*DoctorPatientLink) *DoctorCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPatientLinkIDs(ids...)
}

// AddApprovedPatientLinkIDs adds the "approved_patient_links" edge to the DoctorPatientLink entity by IDs.
func (_c *DoctorCreate) AddApprovedPatientLinkIDs(ids ...uuid.UUID) *DoctorCreate {
	_c.mutation.AddApprovedPatientLinkIDs(ids...)
	return _c
}

// AddApprovedPatientLinks adds the "approved_patient_links" edges to the DoctorPatientLink entity.
func (_c *DoctorCreate) AddApprovedPatientLinks(v ...*DoctorPatientLink) *DoctorCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddApprovedPatientLinkIDs(ids...)
}

// AddEntryShareIDs adds the "entry_shares" edge to the EntryShare entity by IDs.
func (_c *DoctorCreate) AddEntryShareIDs(ids ...uuid.UUID) *DoctorCreate {
	_c.mutation.AddEntryShareIDs(ids...)
	return _c
}

// AddEntryShares adds the "entry_shares" edges to the EntryShare entity.
func (_c *DoctorCreate) AddEntryShares(v ...*EntryShare) *DoctorCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEntryShareIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_c *DoctorCreate) AddCommentIDs(ids ...uuid.UUID) *DoctorCreate {
	_c.mutation.AddCommentIDs(ids...)
	return _c
}

// AddComments adds the "comments" edges to the Comment entity.
func (_c *DoctorCreate) AddComments(v ...*Comment) *DoctorCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommentIDs(ids...)
}

// AddCreatedAnalysisJobIDs adds the "created_analysis_jobs" edge to the AnalysisJob entity by IDs.
func (_c *DoctorCreate) AddCreatedAnalysisJobIDs(ids ...uuid.UUID) *DoctorCreate {
	_c.mutation.AddCreatedAnalysisJobIDs(ids...)
	return _c
}

// AddCreatedAnalysisJobs adds the "created_analysis_jobs" edges to the AnalysisJob entity.
func (_c *DoctorCreate) AddCreatedAnalysisJobs(v ...*AnalysisJob) *DoctorCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCreatedAnalysisJobIDs(ids...)
}

// Mutation returns the DoctorMutation object of the builder.
func (_c *DoctorCreate) Mutation() *DoctorMutation {
	return _c.mutation
}

// Save creates the Doctor in the database.
func (_c *DoctorCreate) Save(ctx context.Context) (*Doctor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DoctorCreate) SaveX(ctx context.Context) *Doctor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DoctorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DoctorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DoctorCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := doctor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := doctor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := doctor.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := doctor.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DoctorCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Doctor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Doctor.updated_at"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Doctor.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := doctor.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Doctor.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "Doctor.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := doctor.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Doctor.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Doctor.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := doctor.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Doctor.role": %w`, err)}
		}
	}
	return nil
}

func (_c *DoctorCreate) sqlSave(ctx context.Context) (*Doctor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DoctorCreate) createSpec() (*Doctor, *sqlgraph.CreateSpec) {
	var (
		_node = &Doctor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(doctor.Table, sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(doctor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(doctor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(doctor.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(doctor.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(doctor.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if nodes := _c.mutation.PracticeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctor.PracticeTable,
			Columns: []string{doctor.PracticeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(practice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PracticeID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PatientLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.PatientLinksTable,
			Columns: []string{doctor.PatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ApprovedPatientLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.ApprovedPatientLinksTable,
			Columns: []string{doctor.ApprovedPatientLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctorpatientlink.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntrySharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.EntrySharesTable,
			Columns: []string{doctor.EntrySharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CommentsTable,
			Columns: []string{doctor.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatedAnalysisJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.CreatedAnalysisJobsTable,
			Columns: []string{doctor.CreatedAnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DoctorCreateBulk is the builder for creating many Doctor entities in bulk.
type DoctorCreateBulk struct {
	config
	err      error
	builders []*DoctorCreate
}

// Save creates the Doctor entities in the database.
func (_c *DoctorCreateBulk) Save(ctx context.Context) ([]*Doctor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Doctor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DoctorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DoctorCreateBulk) SaveX(ctx context.Context) []*Doctor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DoctorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DoctorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
