// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/doctor"
	"backend/ent/practice"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Doctor is the model entity for the Doctor schema.
type Doctor struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// bcrypt hash of the doctor's password
	PasswordHash string `json:"-"`
	// Role holds the value of the "role" field.
	Role doctor.Role `json:"role,omitempty"`
	// PracticeID holds the value of the "practice_id" field.
	PracticeID *uuid.UUID `json:"practice_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DoctorQuery when eager-loading is set.
	Edges        DoctorEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DoctorEdges holds the relations/edges for other nodes in the graph.
type DoctorEdges struct {
	// Doctor belongs to a practice (optional until onboarding).
	Practice *Practice `json:"practice,omitempty"`
	// PatientLinks holds the value of the patient_links edge.
	PatientLinks []*DoctorPatientLink `json:"patient_links,omitempty"`
	// ApprovedPatientLinks holds the value of the approved_patient_links edge.
	ApprovedPatientLinks []*DoctorPatientLink `json:"approved_patient_links,omitempty"`
	// EntryShares holds the value of the entry_shares edge.
	EntryShares []*EntryShare `json:"entry_shares,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// CreatedAnalysisJobs holds the value of the created_analysis_jobs edge.
	CreatedAnalysisJobs []*AnalysisJob `json:"created_analysis_jobs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// PracticeOrErr returns the Practice value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DoctorEdges) PracticeOrErr() (*Practice, error) {
	if e.Practice != nil {
		return e.Practice, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: practice.Label}
	}
	return nil, &NotLoadedError{edge: "practice"}
}

// PatientLinksOrErr returns the PatientLinks value or an error if the edge
// was not loaded in eager-loading.
func (e DoctorEdges) PatientLinksOrErr() ([]*DoctorPatientLink, error) {
	if e.loadedTypes[1] {
		return e.PatientLinks, nil
	}
	return nil, &NotLoadedError{edge: "patient_links"}
}

// ApprovedPatientLinksOrErr returns the ApprovedPatientLinks value or an error if the edge
// was not loaded in eager-loading.
func (e DoctorEdges) ApprovedPatientLinksOrErr() ([]*DoctorPatientLink, error) {
	if e.loadedTypes[2] {
		return e.ApprovedPatientLinks, nil
	}
	return nil, &NotLoadedError{edge: "approved_patient_links"}
}

// EntrySharesOrErr returns the EntryShares value or an error if the edge
// was not loaded in eager-loading.
func (e DoctorEdges) EntrySharesOrErr() ([]*EntryShare, error) {
	if e.loadedTypes[3] {
		return e.EntryShares, nil
	}
	return nil, &NotLoadedError{edge: "entry_shares"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e DoctorEdges) CommentsOrErr() ([]*Comment, error) {
	if e.loadedTypes[4] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// CreatedAnalysisJobsOrErr returns the CreatedAnalysisJobs value or an error if the edge
// was not loaded in eager-loading.
func (e DoctorEdges) CreatedAnalysisJobsOrErr() ([]*AnalysisJob, error) {
	if e.loadedTypes[5] {
		return e.CreatedAnalysisJobs, nil
	}
	return nil, &NotLoadedError{edge: "created_analysis_jobs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Doctor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case doctor.FieldPracticeID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case doctor.FieldEmail, doctor.FieldDisplayName, doctor.FieldPasswordHash, doctor.FieldRole:
			values[i] = new(sql.NullString)
		case doctor.FieldCreatedAt, doctor.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case doctor.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Doctor fields.
func (_m *Doctor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case doctor.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case doctor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case doctor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case doctor.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case doctor.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case doctor.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case doctor.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = doctor.Role(value.String)
			}
		case doctor.FieldPracticeID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field practice_id", values[i])
			} else if value.Valid {
				_m.PracticeID = new(uuid.UUID)
				*_m.PracticeID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Doctor.
// This includes values selected through modifiers, order, etc.
func (_m *Doctor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPractice queries the "practice" edge of the Doctor entity.
func (_m *Doctor) QueryPractice() *PracticeQuery {
	return NewDoctorClient(_m.config).QueryPractice(_m)
}

// QueryPatientLinks queries the "patient_links" edge of the Doctor entity.
func (_m *Doctor) QueryPatientLinks() *DoctorPatientLinkQuery {
	return NewDoctorClient(_m.config).QueryPatientLinks(_m)
}

// QueryApprovedPatientLinks queries the "approved_patient_links" edge of the Doctor entity.
func (_m *Doctor) QueryApprovedPatientLinks() *DoctorPatientLinkQuery {
	return NewDoctorClient(_m.config).QueryApprovedPatientLinks(_m)
}

// QueryEntryShares queries the "entry_shares" edge of the Doctor entity.
func (_m *Doctor) QueryEntryShares() *EntryShareQuery {
	return NewDoctorClient(_m.config).QueryEntryShares(_m)
}

// QueryComments queries the "comments" edge of the Doctor entity.
func (_m *Doctor) QueryComments() *CommentQuery {
	return NewDoctorClient(_m.config).QueryComments(_m)
}

// QueryCreatedAnalysisJobs queries the "created_analysis_jobs" edge of the Doctor entity.
func (_m *Doctor) QueryCreatedAnalysisJobs() *AnalysisJobQuery {
	return NewDoctorClient(_m.config).QueryCreatedAnalysisJobs(_m)
}

// Update returns a builder for updating this Doctor.
// Note that you need to call Doctor.Unwrap() before calling this method if this Doctor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Doctor) Update() *DoctorUpdateOne {
	return NewDoctorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Doctor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Doctor) Unwrap() *Doctor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Doctor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Doctor) String() string {
	var builder strings.Builder
	builder.WriteString("Doctor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	if v := _m.PracticeID; v != nil {
		builder.WriteString("practice_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Doctors is a parsable slice of Doctor.
type Doctors []*Doctor
