// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/entry"
	"backend/ent/patient"
	"backend/ent/schema"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Entry is the model entity for the Entry schema.
type Entry struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PatientID holds the value of the "patient_id" field.
	PatientID uuid.UUID `json:"patient_id,omitempty"`
	// HappenedAt holds the value of the "happened_at" field.
	HappenedAt time.Time `json:"happened_at,omitempty"`
	// Situation holds the value of the "situation" field.
	Situation *string `json:"situation,omitempty"`
	// Emotions holds the value of the "emotions" field.
	Emotions []schema.Emotion `json:"emotions,omitempty"`
	// Triggers holds the value of the "triggers" field.
	Triggers []string `json:"triggers,omitempty"`
	// Techniques holds the value of the "techniques" field.
	Techniques []string `json:"techniques,omitempty"`
	// StutterFrequency holds the value of the "stutter_frequency" field.
	StutterFrequency *int `json:"stutter_frequency,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []string `json:"tags,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntryQuery when eager-loading is set.
	Edges        EntryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EntryEdges holds the relations/edges for other nodes in the graph.
type EntryEdges struct {
	// Patient holds the value of the patient edge.
	Patient *Patient `json:"patient,omitempty"`
	// Shares holds the value of the shares edge.
	Shares []*EntryShare `json:"shares,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// AnalysisJobs holds the value of the analysis_jobs edge.
	AnalysisJobs []*AnalysisJob `json:"analysis_jobs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// PatientOrErr returns the Patient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntryEdges) PatientOrErr() (*Patient, error) {
	if e.Patient != nil {
		return e.Patient, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: patient.Label}
	}
	return nil, &NotLoadedError{edge: "patient"}
}

// SharesOrErr returns the Shares value or an error if the edge
// was not loaded in eager-loading.
func (e EntryEdges) SharesOrErr() ([]*EntryShare, error) {
	if e.loadedTypes[1] {
		return e.Shares, nil
	}
	return nil, &NotLoadedError{edge: "shares"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e EntryEdges) CommentsOrErr() ([]*Comment, error) {
	if e.loadedTypes[2] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// AnalysisJobsOrErr returns the AnalysisJobs value or an error if the edge
// was not loaded in eager-loading.
func (e EntryEdges) AnalysisJobsOrErr() ([]*AnalysisJob, error) {
	if e.loadedTypes[3] {
		return e.AnalysisJobs, nil
	}
	return nil, &NotLoadedError{edge: "analysis_jobs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Entry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entry.FieldEmotions, entry.FieldTriggers, entry.FieldTechniques, entry.FieldTags:
			values[i] = new([]byte)
		case entry.FieldStutterFrequency:
			values[i] = new(sql.NullInt64)
		case entry.FieldSituation, entry.FieldNotes:
			values[i] = new(sql.NullString)
		case entry.FieldCreatedAt, entry.FieldUpdatedAt, entry.FieldHappenedAt:
			values[i] = new(sql.NullTime)
		case entry.FieldID, entry.FieldPatientID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Entry fields.
func (_m *Entry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entry.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case entry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case entry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case entry.FieldPatientID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field patient_id", values[i])
			} else if value != nil {
				_m.PatientID = *value
			}
		case entry.FieldHappenedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field happened_at", values[i])
			} else if value.Valid {
				_m.HappenedAt = value.Time
			}
		case entry.FieldSituation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field situation", values[i])
			} else if value.Valid {
				_m.Situation = new(string)
				*_m.Situation = value.String
			}
		case entry.FieldEmotions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field emotions", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Emotions); err != nil {
					return fmt.Errorf("unmarshal field emotions: %w", err)
				}
			}
		case entry.FieldTriggers:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field triggers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Triggers); err != nil {
					return fmt.Errorf("unmarshal field triggers: %w", err)
				}
			}
		case entry.FieldTechniques:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field techniques", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Techniques); err != nil {
					return fmt.Errorf("unmarshal field techniques: %w", err)
				}
			}
		case entry.FieldStutterFrequency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stutter_frequency", values[i])
			} else if value.Valid {
				_m.StutterFrequency = new(int)
				*_m.StutterFrequency = int(value.Int64)
			}
		case entry.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case entry.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Entry.
// This includes values selected through modifiers, order, etc.
func (_m *Entry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPatient queries the "patient" edge of the Entry entity.
func (_m *Entry) QueryPatient() *PatientQuery {
	return NewEntryClient(_m.config).QueryPatient(_m)
}

// QueryShares queries the "shares" edge of the Entry entity.
func (_m *Entry) QueryShares() *EntryShareQuery {
	return NewEntryClient(_m.config).QueryShares(_m)
}

// QueryComments queries the "comments" edge of the Entry entity.
func (_m *Entry) QueryComments() *CommentQuery {
	return NewEntryClient(_m.config).QueryComments(_m)
}

// QueryAnalysisJobs queries the "analysis_jobs" edge of the Entry entity.
func (_m *Entry) QueryAnalysisJobs() *AnalysisJobQuery {
	return NewEntryClient(_m.config).QueryAnalysisJobs(_m)
}

// Update returns a builder for updating this Entry.
// Note that you need to call Entry.Unwrap() before calling this method if this Entry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Entry) Update() *EntryUpdateOne {
	return NewEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Entry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Entry) Unwrap() *Entry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Entry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Entry) String() string {
	var builder strings.Builder
	builder.WriteString("Entry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("patient_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PatientID))
	builder.WriteString(", ")
	builder.WriteString("happened_at=")
	builder.WriteString(_m.HappenedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Situation; v != nil {
		builder.WriteString("situation=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("emotions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Emotions))
	builder.WriteString(", ")
	builder.WriteString("triggers=")
	builder.WriteString(fmt.Sprintf("%v", _m.Triggers))
	builder.WriteString(", ")
	builder.WriteString("techniques=")
	builder.WriteString(fmt.Sprintf("%v", _m.Techniques))
	builder.WriteString(", ")
	if v := _m.StutterFrequency; v != nil {
		builder.WriteString("stutter_frequency=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteByte(')')
	return builder.String()
}

// Entries is a parsable slice of Entry.
type Entries []*Entry
