// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/doctor"
	"backend/ent/entry"
	"backend/ent/entryshare"
	"backend/ent/patient"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// EntryShareCreate is the builder for creating a EntryShare entity.
type EntryShareCreate struct {
	config
	mutation *EntryShareMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntryShareCreate) SetCreatedAt(v time.Time) *EntryShareCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntryShareCreate) SetNillableCreatedAt(v *time.Time) *EntryShareCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EntryShareCreate) SetUpdatedAt(v time.Time) *EntryShareCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EntryShareCreate) SetNillableUpdatedAt(v *time.Time) *EntryShareCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEntryID sets the "entry_id" field.
func (_c *EntryShareCreate) SetEntryID(v uuid.UUID) *EntryShareCreate {
	_c.mutation.SetEntryID(v)
	return _c
}

// SetSharedByPatientID sets the "shared_by_patient_id" field.
func (_c *EntryShareCreate) SetSharedByPatientID(v uuid.UUID) *EntryShareCreate {
	_c.mutation.SetSharedByPatientID(v)
	return _c
}

// SetSharedWithDoctorID sets the "shared_with_doctor_id" field.
func (_c *EntryShareCreate) SetSharedWithDoctorID(v uuid.UUID) *EntryShareCreate {
	_c.mutation.SetSharedWithDoctorID(v)
	return _c
}

// SetSharedAt sets the "shared_at" field.
func (_c *EntryShareCreate) SetSharedAt(v time.Time) *EntryShareCreate {
	_c.mutation.SetSharedAt(v)
	return _c
}

// SetNillableSharedAt sets the "shared_at" field if the given value is not nil.
func (_c *EntryShareCreate) SetNillableSharedAt(v *time.Time) *EntryShareCreate {
	if v != nil {
		_c.SetSharedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *EntryShareCreate) SetRevokedAt(v time.Time) *EntryShareCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *EntryShareCreate) SetNillableRevokedAt(v *time.Time) *EntryShareCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EntryShareCreate) SetID(v uuid.UUID) *EntryShareCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EntryShareCreate) SetNillableID(v *uuid.UUID) *EntryShareCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetEntry sets the "entry" edge to the Entry entity.
func (_c *EntryShareCreate) SetEntry(v *Entry) *EntryShareCreate {
	return _c.SetEntryID(v.ID)
}

// SetSharedByPatient sets the "shared_by_patient" edge to the Patient entity.
func (_c *EntryShareCreate) SetSharedByPatient(v *Patient) *EntryShareCreate {
	return _c.SetSharedByPatientID(v.ID)
}

// SetSharedWithDoctor sets the "shared_with_doctor" edge to the Doctor entity.
func (_c *EntryShareCreate) SetSharedWithDoctor(v *Doctor) *EntryShareCreate {
	return _c.SetSharedWithDoctorID(v.ID)
}

// Mutation returns the EntryShareMutation object of the builder.
func (_c *EntryShareCreate) Mutation() *EntryShareMutation {
	return _c.mutation
}

// Save creates the EntryShare in the database.
func (_c *EntryShareCreate) Save(ctx context.Context) (*EntryShare, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntryShareCreate) SaveX(ctx context.Context) *EntryShare {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntryShareCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntryShareCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntryShareCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entryshare.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := entryshare.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SharedAt(); !ok {
		v := entryshare.DefaultSharedAt()
		_c.mutation.SetSharedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := entryshare.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntryShareCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EntryShare.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EntryShare.updated_at"`)}
	}
	if _, ok := _c.mutation.EntryID(); !ok {
		return &ValidationError{Name: "entry_id", err: errors.New(`ent: missing required field "EntryShare.entry_id"`)}
	}
	if _, ok := _c.mutation.SharedByPatientID(); !ok {
		return &ValidationError{Name: "shared_by_patient_id", err: errors.New(`ent: missing required field "EntryShare.shared_by_patient_id"`)}
	}
	if _, ok := _c.mutation.SharedWithDoctorID(); !ok {
		return &ValidationError{Name: "shared_with_doctor_id", err: errors.New(`ent: missing required field "EntryShare.shared_with_doctor_id"`)}
	}
	if _, ok := _c.mutation.SharedAt(); !ok {
		return &ValidationError{Name: "shared_at", err: errors.New(`ent: missing required field "EntryShare.shared_at"`)}
	}
	if len(_c.mutation.EntryIDs()) == 0 {
		return &ValidationError{Name: "entry", err: errors.New(`ent: missing required edge "EntryShare.entry"`)}
	}
	if len(_c.mutation.SharedByPatientIDs()) == 0 {
		return &ValidationError{Name: "shared_by_patient", err: errors.New(`ent: missing required edge "EntryShare.shared_by_patient"`)}
	}
	if len(_c.mutation.SharedWithDoctorIDs()) == 0 {
		return &ValidationError{Name: "shared_with_doctor", err: errors.New(`ent: missing required edge "EntryShare.shared_with_doctor"`)}
	}
	return nil
}

func (_c *EntryShareCreate) sqlSave(ctx context.Context) (*EntryShare, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntryShareCreate) createSpec() (*EntryShare, *sqlgraph.CreateSpec) {
	var (
		_node = &EntryShare{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entryshare.Table, sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entryshare.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(entryshare.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SharedAt(); ok {
		_spec.SetField(entryshare.FieldSharedAt, field.TypeTime, value)
		_node.SharedAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(entryshare.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if nodes := _c.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.EntryTable,
			Columns: []string{entryshare.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SharedByPatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.SharedByPatientTable,
			Columns: []string{entryshare.SharedByPatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SharedByPatientID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SharedWithDoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.SharedWithDoctorTable,
			Columns: []string{entryshare.SharedWithDoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SharedWithDoctorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EntryShareCreateBulk is the builder for creating many EntryShare entities in bulk.
type EntryShareCreateBulk struct {
	config
	err      error
	builders []*EntryShareCreate
}

// Save creates the EntryShare entities in the database.
func (_c *EntryShareCreateBulk) Save(ctx context.Context) ([]*EntryShare, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EntryShare, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntryShareMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntryShareCreateBulk) SaveX(ctx context.Context) []*EntryShare {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntryShareCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntryShareCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
