// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/doctor"
	"backend/ent/entry"
	"backend/ent/entryshare"
	"backend/ent/patient"
	"backend/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// EntryShareUpdate is the builder for updating EntryShare entities.
type EntryShareUpdate struct {
	config
	hooks    []Hook
	mutation *EntryShareMutation
}

// Where appends a list predicates to the EntryShareUpdate builder.
func (_u *EntryShareUpdate) Where(ps ...predicate.EntryShare) *EntryShareUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntryShareUpdate) SetUpdatedAt(v time.Time) *EntryShareUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntryID sets the "entry_id" field.
func (_u *EntryShareUpdate) SetEntryID(v uuid.UUID) *EntryShareUpdate {
	_u.mutation.SetEntryID(v)
	return _u
}

// SetNillableEntryID sets the "entry_id" field if the given value is not nil.
func (_u *EntryShareUpdate) SetNillableEntryID(v *uuid.UUID) *EntryShareUpdate {
	if v != nil {
		_u.SetEntryID(*v)
	}
	return _u
}

// SetSharedByPatientID sets the "shared_by_patient_id" field.
func (_u *EntryShareUpdate) SetSharedByPatientID(v uuid.UUID) *EntryShareUpdate {
	_u.mutation.SetSharedByPatientID(v)
	return _u
}

// SetNillableSharedByPatientID sets the "shared_by_patient_id" field if the given value is not nil.
func (_u *EntryShareUpdate) SetNillableSharedByPatientID(v *uuid.UUID) *EntryShareUpdate {
	if v != nil {
		_u.SetSharedByPatientID(*v)
	}
	return _u
}

// SetSharedWithDoctorID sets the "shared_with_doctor_id" field.
func (_u *EntryShareUpdate) SetSharedWithDoctorID(v uuid.UUID) *EntryShareUpdate {
	_u.mutation.SetSharedWithDoctorID(v)
	return _u
}

// SetNillableSharedWithDoctorID sets the "shared_with_doctor_id" field if the given value is not nil.
func (_u *EntryShareUpdate) SetNillableSharedWithDoctorID(v *uuid.UUID) *EntryShareUpdate {
	if v != nil {
		_u.SetSharedWithDoctorID(*v)
	}
	return _u
}

// SetSharedAt sets the "shared_at" field.
func (_u *EntryShareUpdate) SetSharedAt(v time.Time) *EntryShareUpdate {
	_u.mutation.SetSharedAt(v)
	return _u
}

// SetNillableSharedAt sets the "shared_at" field if the given value is not nil.
func (_u *EntryShareUpdate) SetNillableSharedAt(v *time.Time) *EntryShareUpdate {
	if v != nil {
		_u.SetSharedAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *EntryShareUpdate) SetRevokedAt(v time.Time) *EntryShareUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *EntryShareUpdate) SetNillableRevokedAt(v *time.Time) *EntryShareUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *EntryShareUpdate) ClearRevokedAt() *EntryShareUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetEntry sets the "entry" edge to the Entry entity.
func (_u *EntryShareUpdate) SetEntry(v *Entry) *EntryShareUpdate {
	return _u.SetEntryID(v.ID)
}

// SetSharedByPatient sets the "shared_by_patient" edge to the Patient entity.
func (_u *EntryShareUpdate) SetSharedByPatient(v *Patient) *EntryShareUpdate {
	return _u.SetSharedByPatientID(v.ID)
}

// SetSharedWithDoctor sets the "shared_with_doctor" edge to the Doctor entity.
func (_u *EntryShareUpdate) SetSharedWithDoctor(v *Doctor) *EntryShareUpdate {
	return _u.SetSharedWithDoctorID(v.ID)
}

// Mutation returns the EntryShareMutation object of the builder.
func (_u *EntryShareUpdate) Mutation() *EntryShareMutation {
	return _u.mutation
}

// ClearEntry clears the "entry" edge to the Entry entity.
func (_u *EntryShareUpdate) ClearEntry() *EntryShareUpdate {
	_u.mutation.ClearEntry()
	return _u
}

// ClearSharedByPatient clears the "shared_by_patient" edge to the Patient entity.
func (_u *EntryShareUpdate) ClearSharedByPatient() *EntryShareUpdate {
	_u.mutation.ClearSharedByPatient()
	return _u
}

// ClearSharedWithDoctor clears the "shared_with_doctor" edge to the Doctor entity.
func (_u *EntryShareUpdate) ClearSharedWithDoctor() *EntryShareUpdate {
	_u.mutation.ClearSharedWithDoctor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntryShareUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntryShareUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntryShareUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntryShareUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntryShareUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entryshare.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntryShareUpdate) check() error {
	if _u.mutation.EntryCleared() && len(_u.mutation.EntryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntryShare.entry"`)
	}
	if _u.mutation.SharedByPatientCleared() && len(_u.mutation.SharedByPatientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntryShare.shared_by_patient"`)
	}
	if _u.mutation.SharedWithDoctorCleared() && len(_u.mutation.SharedWithDoctorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntryShare.shared_with_doctor"`)
	}
	return nil
}

func (_u *EntryShareUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entryshare.Table, entryshare.Columns, sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entryshare.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SharedAt(); ok {
		_spec.SetField(entryshare.FieldSharedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(entryshare.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(entryshare.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.EntryTable,
			Columns: []string{entryshare.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.EntryTable,
			Columns: []string{entryshare.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SharedByPatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.SharedByPatientTable,
			Columns: []string{entryshare.SharedByPatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SharedByPatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.SharedByPatientTable,
			Columns: []string{entryshare.SharedByPatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SharedWithDoctorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.SharedWithDoctorTable,
			Columns: []string{entryshare.SharedWithDoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SharedWithDoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.SharedWithDoctorTable,
			Columns: []string{entryshare.SharedWithDoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entryshare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntryShareUpdateOne is the builder for updating a single EntryShare entity.
type EntryShareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntryShareMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntryShareUpdateOne) SetUpdatedAt(v time.Time) *EntryShareUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntryID sets the "entry_id" field.
func (_u *EntryShareUpdateOne) SetEntryID(v uuid.UUID) *EntryShareUpdateOne {
	_u.mutation.SetEntryID(v)
	return _u
}

// SetNillableEntryID sets the "entry_id" field if the given value is not nil.
func (_u *EntryShareUpdateOne) SetNillableEntryID(v *uuid.UUID) *EntryShareUpdateOne {
	if v != nil {
		_u.SetEntryID(*v)
	}
	return _u
}

// SetSharedByPatientID sets the "shared_by_patient_id" field.
func (_u *EntryShareUpdateOne) SetSharedByPatientID(v uuid.UUID) *EntryShareUpdateOne {
	_u.mutation.SetSharedByPatientID(v)
	return _u
}

// SetNillableSharedByPatientID sets the "shared_by_patient_id" field if the given value is not nil.
func (_u *EntryShareUpdateOne) SetNillableSharedByPatientID(v *uuid.UUID) *EntryShareUpdateOne {
	if v != nil {
		_u.SetSharedByPatientID(*v)
	}
	return _u
}

// SetSharedWithDoctorID sets the "shared_with_doctor_id" field.
func (_u *EntryShareUpdateOne) SetSharedWithDoctorID(v uuid.UUID) *EntryShareUpdateOne {
	_u.mutation.SetSharedWithDoctorID(v)
	return _u
}

// SetNillableSharedWithDoctorID sets the "shared_with_doctor_id" field if the given value is not nil.
func (_u *EntryShareUpdateOne) SetNillableSharedWithDoctorID(v *uuid.UUID) *EntryShareUpdateOne {
	if v != nil {
		_u.SetSharedWithDoctorID(*v)
	}
	return _u
}

// SetSharedAt sets the "shared_at" field.
func (_u *EntryShareUpdateOne) SetSharedAt(v time.Time) *EntryShareUpdateOne {
	_u.mutation.SetSharedAt(v)
	return _u
}

// SetNillableSharedAt sets the "shared_at" field if the given value is not nil.
func (_u *EntryShareUpdateOne) SetNillableSharedAt(v *time.Time) *EntryShareUpdateOne {
	if v != nil {
		_u.SetSharedAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *EntryShareUpdateOne) SetRevokedAt(v time.Time) *EntryShareUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *EntryShareUpdateOne) SetNillableRevokedAt(v *time.Time) *EntryShareUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *EntryShareUpdateOne) ClearRevokedAt() *EntryShareUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetEntry sets the "entry" edge to the Entry entity.
func (_u *EntryShareUpdateOne) SetEntry(v *Entry) *EntryShareUpdateOne {
	return _u.SetEntryID(v.ID)
}

// SetSharedByPatient sets the "shared_by_patient" edge to the Patient entity.
func (_u *EntryShareUpdateOne) SetSharedByPatient(v *Patient) *EntryShareUpdateOne {
	return _u.SetSharedByPatientID(v.ID)
}

// SetSharedWithDoctor sets the "shared_with_doctor" edge to the Doctor entity.
func (_u *EntryShareUpdateOne) SetSharedWithDoctor(v *Doctor) *EntryShareUpdateOne {
	return _u.SetSharedWithDoctorID(v.ID)
}

// Mutation returns the EntryShareMutation object of the builder.
func (_u *EntryShareUpdateOne) Mutation() *EntryShareMutation {
	return _u.mutation
}

// ClearEntry clears the "entry" edge to the Entry entity.
func (_u *EntryShareUpdateOne) ClearEntry() *EntryShareUpdateOne {
	_u.mutation.ClearEntry()
	return _u
}

// ClearSharedByPatient clears the "shared_by_patient" edge to the Patient entity.
func (_u *EntryShareUpdateOne) ClearSharedByPatient() *EntryShareUpdateOne {
	_u.mutation.ClearSharedByPatient()
	return _u
}

// ClearSharedWithDoctor clears the "shared_with_doctor" edge to the Doctor entity.
func (_u *EntryShareUpdateOne) ClearSharedWithDoctor() *EntryShareUpdateOne {
	_u.mutation.ClearSharedWithDoctor()
	return _u
}

// Where appends a list predicates to the EntryShareUpdate builder.
func (_u *EntryShareUpdateOne) Where(ps ...predicate.EntryShare) *EntryShareUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntryShareUpdateOne) Select(field string, fields ...string) *EntryShareUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EntryShare entity.
func (_u *EntryShareUpdateOne) Save(ctx context.Context) (*EntryShare, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntryShareUpdateOne) SaveX(ctx context.Context) *EntryShare {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntryShareUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntryShareUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntryShareUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entryshare.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntryShareUpdateOne) check() error {
	if _u.mutation.EntryCleared() && len(_u.mutation.EntryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntryShare.entry"`)
	}
	if _u.mutation.SharedByPatientCleared() && len(_u.mutation.SharedByPatientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntryShare.shared_by_patient"`)
	}
	if _u.mutation.SharedWithDoctorCleared() && len(_u.mutation.SharedWithDoctorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntryShare.shared_with_doctor"`)
	}
	return nil
}

func (_u *EntryShareUpdateOne) sqlSave(ctx context.Context) (_node *EntryShare, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entryshare.Table, entryshare.Columns, sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EntryShare.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entryshare.FieldID)
		for _, f := range fields {
			if !entryshare.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entryshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entryshare.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SharedAt(); ok {
		_spec.SetField(entryshare.FieldSharedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(entryshare.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(entryshare.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.EntryTable,
			Columns: []string{entryshare.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.EntryTable,
			Columns: []string{entryshare.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SharedByPatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.SharedByPatientTable,
			Columns: []string{entryshare.SharedByPatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SharedByPatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.SharedByPatientTable,
			Columns: []string{entryshare.SharedByPatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SharedWithDoctorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.SharedWithDoctorTable,
			Columns: []string{entryshare.SharedWithDoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SharedWithDoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entryshare.SharedWithDoctorTable,
			Columns: []string{entryshare.SharedWithDoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EntryShare{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entryshare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
