// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/doctor"
	"backend/ent/entry"
	"backend/ent/entryshare"
	"backend/ent/patient"
	"backend/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// EntryShareQuery is the builder for querying EntryShare entities.
type EntryShareQuery struct {
	config
	ctx                  *QueryContext
	order                []entryshare.OrderOption
	inters               []Interceptor
	predicates           []predicate.EntryShare
	withEntry            *EntryQuery
	withSharedByPatient  *PatientQuery
	withSharedWithDoctor *DoctorQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntryShareQuery builder.
func (_q *EntryShareQuery) Where(ps ...predicate.EntryShare) *EntryShareQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EntryShareQuery) Limit(limit int) *EntryShareQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EntryShareQuery) Offset(offset int) *EntryShareQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EntryShareQuery) Unique(unique bool) *EntryShareQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EntryShareQuery) Order(o ...entryshare.OrderOption) *EntryShareQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEntry chains the current query on the "entry" edge.
func (_q *EntryShareQuery) QueryEntry() *EntryQuery {
	query := (&EntryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entryshare.Table, entryshare.FieldID, selector),
			sqlgraph.To(entry.Table, entry.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entryshare.EntryTable, entryshare.EntryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySharedByPatient chains the current query on the "shared_by_patient" edge.
func (_q *EntryShareQuery) QuerySharedByPatient() *PatientQuery {
	query := (&PatientClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entryshare.Table, entryshare.FieldID, selector),
			sqlgraph.To(patient.Table, patient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entryshare.SharedByPatientTable, entryshare.SharedByPatientColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySharedWithDoctor chains the current query on the "shared_with_doctor" edge.
func (_q *EntryShareQuery) QuerySharedWithDoctor() *DoctorQuery {
	query := (&DoctorClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entryshare.Table, entryshare.FieldID, selector),
			sqlgraph.To(doctor.Table, doctor.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entryshare.SharedWithDoctorTable, entryshare.SharedWithDoctorColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EntryShare entity from the query.
// Returns a *NotFoundError when no EntryShare was found.
func (_q *EntryShareQuery) First(ctx context.Context) (*EntryShare, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entryshare.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EntryShareQuery) FirstX(ctx context.Context) *EntryShare {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntryShare ID from the query.
// Returns a *NotFoundError when no EntryShare ID was found.
func (_q *EntryShareQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entryshare.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EntryShareQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntryShare entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EntryShare entity is found.
// Returns a *NotFoundError when no EntryShare entities are found.
func (_q *EntryShareQuery) Only(ctx context.Context) (*EntryShare, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entryshare.Label}
	default:
		return nil, &NotSingularError{entryshare.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EntryShareQuery) OnlyX(ctx context.Context) *EntryShare {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntryShare ID in the query.
// Returns a *NotSingularError when more than one EntryShare ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EntryShareQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entryshare.Label}
	default:
		err = &NotSingularError{entryshare.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EntryShareQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntryShares.
func (_q *EntryShareQuery) All(ctx context.Context) ([]*EntryShare, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EntryShare, *EntryShareQuery]()
	return withInterceptors[[]*EntryShare](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EntryShareQuery) AllX(ctx context.Context) []*EntryShare {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntryShare IDs.
func (_q *EntryShareQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(entryshare.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EntryShareQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EntryShareQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EntryShareQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EntryShareQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EntryShareQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EntryShareQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntryShareQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EntryShareQuery) Clone() *EntryShareQuery {
	if _q == nil {
		return nil
	}
	return &EntryShareQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]entryshare.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.EntryShare{}, _q.predicates...),
		withEntry:            _q.withEntry.Clone(),
		withSharedByPatient:  _q.withSharedByPatient.Clone(),
		withSharedWithDoctor: _q.withSharedWithDoctor.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEntry tells the query-builder to eager-load the nodes that are connected to
// the "entry" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EntryShareQuery) WithEntry(opts ...func(*EntryQuery)) *EntryShareQuery {
	query := (&EntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEntry = query
	return _q
}

// WithSharedByPatient tells the query-builder to eager-load the nodes that are connected to
// the "shared_by_patient" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EntryShareQuery) WithSharedByPatient(opts ...func(*PatientQuery)) *EntryShareQuery {
	query := (&PatientClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSharedByPatient = query
	return _q
}

// WithSharedWithDoctor tells the query-builder to eager-load the nodes that are connected to
// the "shared_with_doctor" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EntryShareQuery) WithSharedWithDoctor(opts ...func(*DoctorQuery)) *EntryShareQuery {
	query := (&DoctorClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSharedWithDoctor = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntryShare.Query().
//		GroupBy(entryshare.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EntryShareQuery) GroupBy(field string, fields ...string) *EntryShareGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EntryShareGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = entryshare.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.EntryShare.Query().
//		Select(entryshare.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *EntryShareQuery) Select(fields ...string) *EntryShareSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EntryShareSelect{EntryShareQuery: _q}
	sbuild.label = entryshare.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EntryShareSelect configured with the given aggregations.
func (_q *EntryShareQuery) Aggregate(fns ...AggregateFunc) *EntryShareSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EntryShareQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !entryshare.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EntryShareQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EntryShare, error) {
	var (
		nodes       = []*EntryShare{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withEntry != nil,
			_q.withSharedByPatient != nil,
			_q.withSharedWithDoctor != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EntryShare).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EntryShare{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEntry; query != nil {
		if err := _q.loadEntry(ctx, query, nodes, nil,
			func(n *EntryShare, e *Entry) { n.Edges.Entry = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSharedByPatient; query != nil {
		if err := _q.loadSharedByPatient(ctx, query, nodes, nil,
			func(n *EntryShare, e *Patient) { n.Edges.SharedByPatient = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSharedWithDoctor; query != nil {
		if err := _q.loadSharedWithDoctor(ctx, query, nodes, nil,
			func(n *EntryShare, e *Doctor) { n.Edges.SharedWithDoctor = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EntryShareQuery) loadEntry(ctx context.Context, query *EntryQuery, nodes []*EntryShare, init func(*EntryShare), assign func(*EntryShare, *Entry)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*EntryShare)
	for i := range nodes {
		fk := nodes[i].EntryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(entry.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "entry_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EntryShareQuery) loadSharedByPatient(ctx context.Context, query *PatientQuery, nodes []*EntryShare, init func(*EntryShare), assign func(*EntryShare, *Patient)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*EntryShare)
	for i := range nodes {
		fk := nodes[i].SharedByPatientID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(patient.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "shared_by_patient_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EntryShareQuery) loadSharedWithDoctor(ctx context.Context, query *DoctorQuery, nodes []*EntryShare, init func(*EntryShare), assign func(*EntryShare, *Doctor)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*EntryShare)
	for i := range nodes {
		fk := nodes[i].SharedWithDoctorID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(doctor.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "shared_with_doctor_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *EntryShareQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EntryShareQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(entryshare.Table, entryshare.Columns, sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entryshare.FieldID)
		for i := range fields {
			if fields[i] != entryshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withEntry != nil {
			_spec.Node.AddColumnOnce(entryshare.FieldEntryID)
		}
		if _q.withSharedByPatient != nil {
			_spec.Node.AddColumnOnce(entryshare.FieldSharedByPatientID)
		}
		if _q.withSharedWithDoctor != nil {
			_spec.Node.AddColumnOnce(entryshare.FieldSharedWithDoctorID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EntryShareQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(entryshare.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = entryshare.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntryShareGroupBy is the group-by builder for EntryShare entities.
type EntryShareGroupBy struct {
	selector
	build *EntryShareQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EntryShareGroupBy) Aggregate(fns ...AggregateFunc) *EntryShareGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EntryShareGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntryShareQuery, *EntryShareGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EntryShareGroupBy) sqlScan(ctx context.Context, root *EntryShareQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EntryShareSelect is the builder for selecting fields of EntryShare entities.
type EntryShareSelect struct {
	*EntryShareQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EntryShareSelect) Aggregate(fns ...AggregateFunc) *EntryShareSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EntryShareSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EntryShareQuery, *EntryShareSelect](ctx, _s.EntryShareQuery, _s, _s.inters, v)
}

func (_s *EntryShareSelect) sqlScan(ctx context.Context, root *EntryShareQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
