// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/analysisjob"
	"backend/ent/comment"
	"backend/ent/entry"
	"backend/ent/entryshare"
	"backend/ent/patient"
	"backend/ent/predicate"
	"backend/ent/schema"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// EntryUpdate is the builder for updating Entry entities.
type EntryUpdate struct {
	config
	hooks    []Hook
	mutation *EntryMutation
}

// Where appends a list predicates to the EntryUpdate builder.
func (_u *EntryUpdate) Where(ps ...predicate.Entry) *EntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntryUpdate) SetUpdatedAt(v time.Time) *EntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPatientID sets the "patient_id" field.
func (_u *EntryUpdate) SetPatientID(v uuid.UUID) *EntryUpdate {
	_u.mutation.SetPatientID(v)
	return _u
}

// SetNillablePatientID sets the "patient_id" field if the given value is not nil.
func (_u *EntryUpdate) SetNillablePatientID(v *uuid.UUID) *EntryUpdate {
	if v != nil {
		_u.SetPatientID(*v)
	}
	return _u
}

// SetHappenedAt sets the "happened_at" field.
func (_u *EntryUpdate) SetHappenedAt(v time.Time) *EntryUpdate {
	_u.mutation.SetHappenedAt(v)
	return _u
}

// SetNillableHappenedAt sets the "happened_at" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableHappenedAt(v *time.Time) *EntryUpdate {
	if v != nil {
		_u.SetHappenedAt(*v)
	}
	return _u
}

// SetSituation sets the "situation" field.
func (_u *EntryUpdate) SetSituation(v string) *EntryUpdate {
	_u.mutation.SetSituation(v)
	return _u
}

// SetNillableSituation sets the "situation" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableSituation(v *string) *EntryUpdate {
	if v != nil {
		_u.SetSituation(*v)
	}
	return _u
}

// ClearSituation clears the value of the "situation" field.
func (_u *EntryUpdate) ClearSituation() *EntryUpdate {
	_u.mutation.ClearSituation()
	return _u
}

// SetEmotions sets the "emotions" field.
func (_u *EntryUpdate) SetEmotions(v []schema.Emotion) *EntryUpdate {
	_u.mutation.SetEmotions(v)
	return _u
}

// AppendEmotions appends value to the "emotions" field.
func (_u *EntryUpdate) AppendEmotions(v []schema.Emotion) *EntryUpdate {
	_u.mutation.AppendEmotions(v)
	return _u
}

// ClearEmotions clears the value of the "emotions" field.
func (_u *EntryUpdate) ClearEmotions() *EntryUpdate {
	_u.mutation.ClearEmotions()
	return _u
}

// SetTriggers sets the "triggers" field.
func (_u *EntryUpdate) SetTriggers(v []string) *EntryUpdate {
	_u.mutation.SetTriggers(v)
	return _u
}

// AppendTriggers appends value to the "triggers" field.
func (_u *EntryUpdate) AppendTriggers(v []string) *EntryUpdate {
	_u.mutation.AppendTriggers(v)
	return _u
}

// ClearTriggers clears the value of the "triggers" field.
func (_u *EntryUpdate) ClearTriggers() *EntryUpdate {
	_u.mutation.ClearTriggers()
	return _u
}

// SetTechniques sets the "techniques" field.
func (_u *EntryUpdate) SetTechniques(v []string) *EntryUpdate {
	_u.mutation.SetTechniques(v)
	return _u
}

// AppendTechniques appends value to the "techniques" field.
func (_u *EntryUpdate) AppendTechniques(v []string) *EntryUpdate {
	_u.mutation.AppendTechniques(v)
	return _u
}

// ClearTechniques clears the value of the "techniques" field.
func (_u *EntryUpdate) ClearTechniques() *EntryUpdate {
	_u.mutation.ClearTechniques()
	return _u
}

// SetStutterFrequency sets the "stutter_frequency" field.
func (_u *EntryUpdate) SetStutterFrequency(v int) *EntryUpdate {
	_u.mutation.ResetStutterFrequency()
	_u.mutation.SetStutterFrequency(v)
	return _u
}

// SetNillableStutterFrequency sets the "stutter_frequency" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableStutterFrequency(v *int) *EntryUpdate {
	if v != nil {
		_u.SetStutterFrequency(*v)
	}
	return _u
}

// AddStutterFrequency adds value to the "stutter_frequency" field.
func (_u *EntryUpdate) AddStutterFrequency(v int) *EntryUpdate {
	_u.mutation.AddStutterFrequency(v)
	return _u
}

// ClearStutterFrequency clears the value of the "stutter_frequency" field.
func (_u *EntryUpdate) ClearStutterFrequency() *EntryUpdate {
	_u.mutation.ClearStutterFrequency()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EntryUpdate) SetNotes(v string) *EntryUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EntryUpdate) SetNillableNotes(v *string) *EntryUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *EntryUpdate) ClearNotes() *EntryUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetTags sets the "tags" field.
func (_u *EntryUpdate) SetTags(v []string) *EntryUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *EntryUpdate) AppendTags(v []string) *EntryUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *EntryUpdate) ClearTags() *EntryUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_u *EntryUpdate) SetPatient(v *Patient) *EntryUpdate {
	return _u.SetPatientID(v.ID)
}

// AddShareIDs adds the "shares" edge to the EntryShare entity by IDs.
func (_u *EntryUpdate) AddShareIDs(ids ...uuid.UUID) *EntryUpdate {
	_u.mutation.AddShareIDs(ids...)
	return _u
}

// AddShares adds the "shares" edges to the EntryShare entity.
func (_u *EntryUpdate) AddShares(v ...*EntryShare) *EntryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShareIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *EntryUpdate) AddCommentIDs(ids ...uuid.UUID) *EntryUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *EntryUpdate) AddComments(v ...*Comment) *EntryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddAnalysisJobIDs adds the "analysis_jobs" edge to the AnalysisJob entity by IDs.
func (_u *EntryUpdate) AddAnalysisJobIDs(ids ...uuid.UUID) *EntryUpdate {
	_u.mutation.AddAnalysisJobIDs(ids...)
	return _u
}

// AddAnalysisJobs adds the "analysis_jobs" edges to the AnalysisJob entity.
func (_u *EntryUpdate) AddAnalysisJobs(v ...*AnalysisJob) *EntryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnalysisJobIDs(ids...)
}

// Mutation returns the EntryMutation object of the builder.
func (_u *EntryUpdate) Mutation() *EntryMutation {
	return _u.mutation
}

// ClearPatient clears the "patient" edge to the Patient entity.
func (_u *EntryUpdate) ClearPatient() *EntryUpdate {
	_u.mutation.ClearPatient()
	return _u
}

// ClearShares clears all "shares" edges to the EntryShare entity.
func (_u *EntryUpdate) ClearShares() *EntryUpdate {
	_u.mutation.ClearShares()
	return _u
}

// RemoveShareIDs removes the "shares" edge to EntryShare entities by IDs.
func (_u *EntryUpdate) RemoveShareIDs(ids ...uuid.UUID) *EntryUpdate {
	_u.mutation.RemoveShareIDs(ids...)
	return _u
}

// RemoveShares removes "shares" edges to EntryShare entities.
func (_u *EntryUpdate) RemoveShares(v ...*EntryShare) *EntryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShareIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *EntryUpdate) ClearComments() *EntryUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *EntryUpdate) RemoveCommentIDs(ids ...uuid.UUID) *EntryUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *EntryUpdate) RemoveComments(v ...*Comment) *EntryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearAnalysisJobs clears all "analysis_jobs" edges to the AnalysisJob entity.
func (_u *EntryUpdate) ClearAnalysisJobs() *EntryUpdate {
	_u.mutation.ClearAnalysisJobs()
	return _u
}

// RemoveAnalysisJobIDs removes the "analysis_jobs" edge to AnalysisJob entities by IDs.
func (_u *EntryUpdate) RemoveAnalysisJobIDs(ids ...uuid.UUID) *EntryUpdate {
	_u.mutation.RemoveAnalysisJobIDs(ids...)
	return _u
}

// RemoveAnalysisJobs removes "analysis_jobs" edges to AnalysisJob entities.
func (_u *EntryUpdate) RemoveAnalysisJobs(v ...*AnalysisJob) *EntryUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnalysisJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntryUpdate) check() error {
	if _u.mutation.PatientCleared() && len(_u.mutation.PatientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Entry.patient"`)
	}
	return nil
}

func (_u *EntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entry.Table, entry.Columns, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HappenedAt(); ok {
		_spec.SetField(entry.FieldHappenedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Situation(); ok {
		_spec.SetField(entry.FieldSituation, field.TypeString, value)
	}
	if _u.mutation.SituationCleared() {
		_spec.ClearField(entry.FieldSituation, field.TypeString)
	}
	if value, ok := _u.mutation.Emotions(); ok {
		_spec.SetField(entry.FieldEmotions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmotions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entry.FieldEmotions, value)
		})
	}
	if _u.mutation.EmotionsCleared() {
		_spec.ClearField(entry.FieldEmotions, field.TypeJSON)
	}
	if value, ok := _u.mutation.Triggers(); ok {
		_spec.SetField(entry.FieldTriggers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTriggers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entry.FieldTriggers, value)
		})
	}
	if _u.mutation.TriggersCleared() {
		_spec.ClearField(entry.FieldTriggers, field.TypeJSON)
	}
	if value, ok := _u.mutation.Techniques(); ok {
		_spec.SetField(entry.FieldTechniques, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTechniques(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entry.FieldTechniques, value)
		})
	}
	if _u.mutation.TechniquesCleared() {
		_spec.ClearField(entry.FieldTechniques, field.TypeJSON)
	}
	if value, ok := _u.mutation.StutterFrequency(); ok {
		_spec.SetField(entry.FieldStutterFrequency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStutterFrequency(); ok {
		_spec.AddField(entry.FieldStutterFrequency, field.TypeInt, value)
	}
	if _u.mutation.StutterFrequencyCleared() {
		_spec.ClearField(entry.FieldStutterFrequency, field.TypeInt)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(entry.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(entry.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(entry.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entry.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(entry.FieldTags, field.TypeJSON)
	}
	if _u.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.PatientTable,
			Columns: []string{entry.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.PatientTable,
			Columns: []string{entry.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.SharesTable,
			Columns: []string{entry.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSharesIDs(); len(nodes) > 0 && !_u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.SharesTable,
			Columns: []string{entry.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.SharesTable,
			Columns: []string{entry.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.CommentsTable,
			Columns: []string{entry.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.CommentsTable,
			Columns: []string{entry.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.CommentsTable,
			Columns: []string{entry.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnalysisJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.AnalysisJobsTable,
			Columns: []string{entry.AnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnalysisJobsIDs(); len(nodes) > 0 && !_u.mutation.AnalysisJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.AnalysisJobsTable,
			Columns: []string{entry.AnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnalysisJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.AnalysisJobsTable,
			Columns: []string{entry.AnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntryUpdateOne is the builder for updating a single Entry entity.
type EntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntryUpdateOne) SetUpdatedAt(v time.Time) *EntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPatientID sets the "patient_id" field.
func (_u *EntryUpdateOne) SetPatientID(v uuid.UUID) *EntryUpdateOne {
	_u.mutation.SetPatientID(v)
	return _u
}

// SetNillablePatientID sets the "patient_id" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillablePatientID(v *uuid.UUID) *EntryUpdateOne {
	if v != nil {
		_u.SetPatientID(*v)
	}
	return _u
}

// SetHappenedAt sets the "happened_at" field.
func (_u *EntryUpdateOne) SetHappenedAt(v time.Time) *EntryUpdateOne {
	_u.mutation.SetHappenedAt(v)
	return _u
}

// SetNillableHappenedAt sets the "happened_at" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableHappenedAt(v *time.Time) *EntryUpdateOne {
	if v != nil {
		_u.SetHappenedAt(*v)
	}
	return _u
}

// SetSituation sets the "situation" field.
func (_u *EntryUpdateOne) SetSituation(v string) *EntryUpdateOne {
	_u.mutation.SetSituation(v)
	return _u
}

// SetNillableSituation sets the "situation" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableSituation(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetSituation(*v)
	}
	return _u
}

// ClearSituation clears the value of the "situation" field.
func (_u *EntryUpdateOne) ClearSituation() *EntryUpdateOne {
	_u.mutation.ClearSituation()
	return _u
}

// SetEmotions sets the "emotions" field.
func (_u *EntryUpdateOne) SetEmotions(v []schema.Emotion) *EntryUpdateOne {
	_u.mutation.SetEmotions(v)
	return _u
}

// AppendEmotions appends value to the "emotions" field.
func (_u *EntryUpdateOne) AppendEmotions(v []schema.Emotion) *EntryUpdateOne {
	_u.mutation.AppendEmotions(v)
	return _u
}

// ClearEmotions clears the value of the "emotions" field.
func (_u *EntryUpdateOne) ClearEmotions() *EntryUpdateOne {
	_u.mutation.ClearEmotions()
	return _u
}

// SetTriggers sets the "triggers" field.
func (_u *EntryUpdateOne) SetTriggers(v []string) *EntryUpdateOne {
	_u.mutation.SetTriggers(v)
	return _u
}

// AppendTriggers appends value to the "triggers" field.
func (_u *EntryUpdateOne) AppendTriggers(v []string) *EntryUpdateOne {
	_u.mutation.AppendTriggers(v)
	return _u
}

// ClearTriggers clears the value of the "triggers" field.
func (_u *EntryUpdateOne) ClearTriggers() *EntryUpdateOne {
	_u.mutation.ClearTriggers()
	return _u
}

// SetTechniques sets the "techniques" field.
func (_u *EntryUpdateOne) SetTechniques(v []string) *EntryUpdateOne {
	_u.mutation.SetTechniques(v)
	return _u
}

// AppendTechniques appends value to the "techniques" field.
func (_u *EntryUpdateOne) AppendTechniques(v []string) *EntryUpdateOne {
	_u.mutation.AppendTechniques(v)
	return _u
}

// ClearTechniques clears the value of the "techniques" field.
func (_u *EntryUpdateOne) ClearTechniques() *EntryUpdateOne {
	_u.mutation.ClearTechniques()
	return _u
}

// SetStutterFrequency sets the "stutter_frequency" field.
func (_u *EntryUpdateOne) SetStutterFrequency(v int) *EntryUpdateOne {
	_u.mutation.ResetStutterFrequency()
	_u.mutation.SetStutterFrequency(v)
	return _u
}

// SetNillableStutterFrequency sets the "stutter_frequency" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableStutterFrequency(v *int) *EntryUpdateOne {
	if v != nil {
		_u.SetStutterFrequency(*v)
	}
	return _u
}

// AddStutterFrequency adds value to the "stutter_frequency" field.
func (_u *EntryUpdateOne) AddStutterFrequency(v int) *EntryUpdateOne {
	_u.mutation.AddStutterFrequency(v)
	return _u
}

// ClearStutterFrequency clears the value of the "stutter_frequency" field.
func (_u *EntryUpdateOne) ClearStutterFrequency() *EntryUpdateOne {
	_u.mutation.ClearStutterFrequency()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EntryUpdateOne) SetNotes(v string) *EntryUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EntryUpdateOne) SetNillableNotes(v *string) *EntryUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *EntryUpdateOne) ClearNotes() *EntryUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetTags sets the "tags" field.
func (_u *EntryUpdateOne) SetTags(v []string) *EntryUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *EntryUpdateOne) AppendTags(v []string) *EntryUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *EntryUpdateOne) ClearTags() *EntryUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_u *EntryUpdateOne) SetPatient(v *Patient) *EntryUpdateOne {
	return _u.SetPatientID(v.ID)
}

// AddShareIDs adds the "shares" edge to the EntryShare entity by IDs.
func (_u *EntryUpdateOne) AddShareIDs(ids ...uuid.UUID) *EntryUpdateOne {
	_u.mutation.AddShareIDs(ids...)
	return _u
}

// AddShares adds the "shares" edges to the EntryShare entity.
func (_u *EntryUpdateOne) AddShares(v ...*EntryShare) *EntryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShareIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (_u *EntryUpdateOne) AddCommentIDs(ids ...uuid.UUID) *EntryUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the Comment entity.
func (_u *EntryUpdateOne) AddComments(v ...*Comment) *EntryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddAnalysisJobIDs adds the "analysis_jobs" edge to the AnalysisJob entity by IDs.
func (_u *EntryUpdateOne) AddAnalysisJobIDs(ids ...uuid.UUID) *EntryUpdateOne {
	_u.mutation.AddAnalysisJobIDs(ids...)
	return _u
}

// AddAnalysisJobs adds the "analysis_jobs" edges to the AnalysisJob entity.
func (_u *EntryUpdateOne) AddAnalysisJobs(v ...*AnalysisJob) *EntryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnalysisJobIDs(ids...)
}

// Mutation returns the EntryMutation object of the builder.
func (_u *EntryUpdateOne) Mutation() *EntryMutation {
	return _u.mutation
}

// ClearPatient clears the "patient" edge to the Patient entity.
func (_u *EntryUpdateOne) ClearPatient() *EntryUpdateOne {
	_u.mutation.ClearPatient()
	return _u
}

// ClearShares clears all "shares" edges to the EntryShare entity.
func (_u *EntryUpdateOne) ClearShares() *EntryUpdateOne {
	_u.mutation.ClearShares()
	return _u
}

// RemoveShareIDs removes the "shares" edge to EntryShare entities by IDs.
func (_u *EntryUpdateOne) RemoveShareIDs(ids ...uuid.UUID) *EntryUpdateOne {
	_u.mutation.RemoveShareIDs(ids...)
	return _u
}

// RemoveShares removes "shares" edges to EntryShare entities.
func (_u *EntryUpdateOne) RemoveShares(v ...*EntryShare) *EntryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShareIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (_u *EntryUpdateOne) ClearComments() *EntryUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (_u *EntryUpdateOne) RemoveCommentIDs(ids ...uuid.UUID) *EntryUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to Comment entities.
func (_u *EntryUpdateOne) RemoveComments(v ...*Comment) *EntryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearAnalysisJobs clears all "analysis_jobs" edges to the AnalysisJob entity.
func (_u *EntryUpdateOne) ClearAnalysisJobs() *EntryUpdateOne {
	_u.mutation.ClearAnalysisJobs()
	return _u
}

// RemoveAnalysisJobIDs removes the "analysis_jobs" edge to AnalysisJob entities by IDs.
func (_u *EntryUpdateOne) RemoveAnalysisJobIDs(ids ...uuid.UUID) *EntryUpdateOne {
	_u.mutation.RemoveAnalysisJobIDs(ids...)
	return _u
}

// RemoveAnalysisJobs removes "analysis_jobs" edges to AnalysisJob entities.
func (_u *EntryUpdateOne) RemoveAnalysisJobs(v ...*AnalysisJob) *EntryUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnalysisJobIDs(ids...)
}

// Where appends a list predicates to the EntryUpdate builder.
func (_u *EntryUpdateOne) Where(ps ...predicate.Entry) *EntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntryUpdateOne) Select(field string, fields ...string) *EntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Entry entity.
func (_u *EntryUpdateOne) Save(ctx context.Context) (*Entry, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntryUpdateOne) SaveX(ctx context.Context) *Entry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntryUpdateOne) check() error {
	if _u.mutation.PatientCleared() && len(_u.mutation.PatientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Entry.patient"`)
	}
	return nil
}

func (_u *EntryUpdateOne) sqlSave(ctx context.Context) (_node *Entry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entry.Table, entry.Columns, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Entry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entry.FieldID)
		for _, f := range fields {
			if !entry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entry.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.HappenedAt(); ok {
		_spec.SetField(entry.FieldHappenedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Situation(); ok {
		_spec.SetField(entry.FieldSituation, field.TypeString, value)
	}
	if _u.mutation.SituationCleared() {
		_spec.ClearField(entry.FieldSituation, field.TypeString)
	}
	if value, ok := _u.mutation.Emotions(); ok {
		_spec.SetField(entry.FieldEmotions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmotions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entry.FieldEmotions, value)
		})
	}
	if _u.mutation.EmotionsCleared() {
		_spec.ClearField(entry.FieldEmotions, field.TypeJSON)
	}
	if value, ok := _u.mutation.Triggers(); ok {
		_spec.SetField(entry.FieldTriggers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTriggers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entry.FieldTriggers, value)
		})
	}
	if _u.mutation.TriggersCleared() {
		_spec.ClearField(entry.FieldTriggers, field.TypeJSON)
	}
	if value, ok := _u.mutation.Techniques(); ok {
		_spec.SetField(entry.FieldTechniques, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTechniques(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entry.FieldTechniques, value)
		})
	}
	if _u.mutation.TechniquesCleared() {
		_spec.ClearField(entry.FieldTechniques, field.TypeJSON)
	}
	if value, ok := _u.mutation.StutterFrequency(); ok {
		_spec.SetField(entry.FieldStutterFrequency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStutterFrequency(); ok {
		_spec.AddField(entry.FieldStutterFrequency, field.TypeInt, value)
	}
	if _u.mutation.StutterFrequencyCleared() {
		_spec.ClearField(entry.FieldStutterFrequency, field.TypeInt)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(entry.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(entry.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(entry.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entry.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(entry.FieldTags, field.TypeJSON)
	}
	if _u.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.PatientTable,
			Columns: []string{entry.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.PatientTable,
			Columns: []string{entry.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.SharesTable,
			Columns: []string{entry.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSharesIDs(); len(nodes) > 0 && !_u.mutation.SharesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.SharesTable,
			Columns: []string{entry.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SharesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.SharesTable,
			Columns: []string{entry.SharesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.CommentsTable,
			Columns: []string{entry.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.CommentsTable,
			Columns: []string{entry.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.CommentsTable,
			Columns: []string{entry.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnalysisJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.AnalysisJobsTable,
			Columns: []string{entry.AnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnalysisJobsIDs(); len(nodes) > 0 && !_u.mutation.AnalysisJobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.AnalysisJobsTable,
			Columns: []string{entry.AnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnalysisJobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.AnalysisJobsTable,
			Columns: []string{entry.AnalysisJobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(analysisjob.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Entry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
