// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/doctor"
	"backend/ent/entry"
	"backend/ent/entryshare"
	"backend/ent/patient"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// EntryShare is the model entity for the EntryShare schema.
type EntryShare struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// EntryID holds the value of the "entry_id" field.
	EntryID uuid.UUID `json:"entry_id,omitempty"`
	// SharedByPatientID holds the value of the "shared_by_patient_id" field.
	SharedByPatientID uuid.UUID `json:"shared_by_patient_id,omitempty"`
	// SharedWithDoctorID holds the value of the "shared_with_doctor_id" field.
	SharedWithDoctorID uuid.UUID `json:"shared_with_doctor_id,omitempty"`
	// SharedAt holds the value of the "shared_at" field.
	SharedAt time.Time `json:"shared_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntryShareQuery when eager-loading is set.
	Edges        EntryShareEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EntryShareEdges holds the relations/edges for other nodes in the graph.
type EntryShareEdges struct {
	// Entry holds the value of the entry edge.
	Entry *Entry `json:"entry,omitempty"`
	// SharedByPatient holds the value of the shared_by_patient edge.
	SharedByPatient *Patient `json:"shared_by_patient,omitempty"`
	// SharedWithDoctor holds the value of the shared_with_doctor edge.
	SharedWithDoctor *Doctor `json:"shared_with_doctor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// EntryOrErr returns the Entry value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntryShareEdges) EntryOrErr() (*Entry, error) {
	if e.Entry != nil {
		return e.Entry, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: entry.Label}
	}
	return nil, &NotLoadedError{edge: "entry"}
}

// SharedByPatientOrErr returns the SharedByPatient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntryShareEdges) SharedByPatientOrErr() (*Patient, error) {
	if e.SharedByPatient != nil {
		return e.SharedByPatient, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: patient.Label}
	}
	return nil, &NotLoadedError{edge: "shared_by_patient"}
}

// SharedWithDoctorOrErr returns the SharedWithDoctor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntryShareEdges) SharedWithDoctorOrErr() (*Doctor, error) {
	if e.SharedWithDoctor != nil {
		return e.SharedWithDoctor, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: doctor.Label}
	}
	return nil, &NotLoadedError{edge: "shared_with_doctor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntryShare) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entryshare.FieldCreatedAt, entryshare.FieldUpdatedAt, entryshare.FieldSharedAt, entryshare.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		case entryshare.FieldID, entryshare.FieldEntryID, entryshare.FieldSharedByPatientID, entryshare.FieldSharedWithDoctorID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntryShare fields.
func (_m *EntryShare) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entryshare.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case entryshare.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case entryshare.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case entryshare.FieldEntryID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field entry_id", values[i])
			} else if value != nil {
				_m.EntryID = *value
			}
		case entryshare.FieldSharedByPatientID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field shared_by_patient_id", values[i])
			} else if value != nil {
				_m.SharedByPatientID = *value
			}
		case entryshare.FieldSharedWithDoctorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field shared_with_doctor_id", values[i])
			} else if value != nil {
				_m.SharedWithDoctorID = *value
			}
		case entryshare.FieldSharedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field shared_at", values[i])
			} else if value.Valid {
				_m.SharedAt = value.Time
			}
		case entryshare.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EntryShare.
// This includes values selected through modifiers, order, etc.
func (_m *EntryShare) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEntry queries the "entry" edge of the EntryShare entity.
func (_m *EntryShare) QueryEntry() *EntryQuery {
	return NewEntryShareClient(_m.config).QueryEntry(_m)
}

// QuerySharedByPatient queries the "shared_by_patient" edge of the EntryShare entity.
func (_m *EntryShare) QuerySharedByPatient() *PatientQuery {
	return NewEntryShareClient(_m.config).QuerySharedByPatient(_m)
}

// QuerySharedWithDoctor queries the "shared_with_doctor" edge of the EntryShare entity.
func (_m *EntryShare) QuerySharedWithDoctor() *DoctorQuery {
	return NewEntryShareClient(_m.config).QuerySharedWithDoctor(_m)
}

// Update returns a builder for updating this EntryShare.
// Note that you need to call EntryShare.Unwrap() before calling this method if this EntryShare
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EntryShare) Update() *EntryShareUpdateOne {
	return NewEntryShareClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EntryShare entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EntryShare) Unwrap() *EntryShare {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntryShare is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EntryShare) String() string {
	var builder strings.Builder
	builder.WriteString("EntryShare(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("entry_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntryID))
	builder.WriteString(", ")
	builder.WriteString("shared_by_patient_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SharedByPatientID))
	builder.WriteString(", ")
	builder.WriteString("shared_with_doctor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SharedWithDoctorID))
	builder.WriteString(", ")
	builder.WriteString("shared_at=")
	builder.WriteString(_m.SharedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// EntryShares is a parsable slice of EntryShare.
type EntryShares []*EntryShare
