// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/entryshare"
	"backend/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntryShareDelete is the builder for deleting a EntryShare entity.
type EntryShareDelete struct {
	config
	hooks    []Hook
	mutation *EntryShareMutation
}

// Where appends a list predicates to the EntryShareDelete builder.
func (_d *EntryShareDelete) Where(ps ...predicate.EntryShare) *EntryShareDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EntryShareDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EntryShareDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EntryShareDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(entryshare.Table, sqlgraph.NewFieldSpec(entryshare.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EntryShareDeleteOne is the builder for deleting a single EntryShare entity.
type EntryShareDeleteOne struct {
	_d *EntryShareDelete
}

// Where appends a list predicates to the EntryShareDelete builder.
func (_d *EntryShareDeleteOne) Where(ps ...predicate.EntryShare) *EntryShareDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EntryShareDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{entryshare.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EntryShareDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
