// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/doctor"
	"backend/ent/pairingcode"
	"backend/ent/patient"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// PairingCode is the model entity for the PairingCode schema.
type PairingCode struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// DoctorID holds the value of the "doctor_id" field.
	DoctorID uuid.UUID `json:"doctor_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt *time.Time `json:"consumed_at,omitempty"`
	// ConsumedByPatientID holds the value of the "consumed_by_patient_id" field.
	ConsumedByPatientID *uuid.UUID `json:"consumed_by_patient_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PairingCodeQuery when eager-loading is set.
	Edges        PairingCodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PairingCodeEdges holds the relations/edges for other nodes in the graph.
type PairingCodeEdges struct {
	// Doctor holds the value of the doctor edge.
	Doctor *Doctor `json:"doctor,omitempty"`
	// ConsumedByPatient holds the value of the consumed_by_patient edge.
	ConsumedByPatient *Patient `json:"consumed_by_patient,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DoctorOrErr returns the Doctor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PairingCodeEdges) DoctorOrErr() (*Doctor, error) {
	if e.Doctor != nil {
		return e.Doctor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: doctor.Label}
	}
	return nil, &NotLoadedError{edge: "doctor"}
}

// ConsumedByPatientOrErr returns the ConsumedByPatient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PairingCodeEdges) ConsumedByPatientOrErr() (*Patient, error) {
	if e.ConsumedByPatient != nil {
		return e.ConsumedByPatient, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: patient.Label}
	}
	return nil, &NotLoadedError{edge: "consumed_by_patient"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PairingCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pairingcode.FieldConsumedByPatientID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case pairingcode.FieldCode:
			values[i] = new(sql.NullString)
		case pairingcode.FieldCreatedAt, pairingcode.FieldUpdatedAt, pairingcode.FieldExpiresAt, pairingcode.FieldConsumedAt:
			values[i] = new(sql.NullTime)
		case pairingcode.FieldID, pairingcode.FieldDoctorID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PairingCode fields.
func (_m *PairingCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pairingcode.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case pairingcode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pairingcode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case pairingcode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case pairingcode.FieldDoctorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field doctor_id", values[i])
			} else if value != nil {
				_m.DoctorID = *value
			}
		case pairingcode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case pairingcode.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		case pairingcode.FieldConsumedByPatientID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_by_patient_id", values[i])
			} else if value.Valid {
				_m.ConsumedByPatientID = new(uuid.UUID)
				*_m.ConsumedByPatientID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PairingCode.
// This includes values selected through modifiers, order, etc.
func (_m *PairingCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDoctor queries the "doctor" edge of the PairingCode entity.
func (_m *PairingCode) QueryDoctor() *DoctorQuery {
	return NewPairingCodeClient(_m.config).QueryDoctor(_m)
}

// QueryConsumedByPatient queries the "consumed_by_patient" edge of the PairingCode entity.
func (_m *PairingCode) QueryConsumedByPatient() *PatientQuery {
	return NewPairingCodeClient(_m.config).QueryConsumedByPatient(_m)
}

// Update returns a builder for updating this PairingCode.
// Note that you need to call PairingCode.Unwrap() before calling this method if this PairingCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PairingCode) Update() *PairingCodeUpdateOne {
	return NewPairingCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PairingCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PairingCode) Unwrap() *PairingCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PairingCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PairingCode) String() string {
	var builder strings.Builder
	builder.WriteString("PairingCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("doctor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DoctorID))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ConsumedByPatientID; v != nil {
		builder.WriteString("consumed_by_patient_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PairingCodes is a parsable slice of PairingCode.
type PairingCodes []*PairingCode
