// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/doctor"
	"backend/ent/pairingcode"
	"backend/ent/patient"
	"backend/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PairingCodeUpdate is the builder for updating PairingCode entities.
type PairingCodeUpdate struct {
	config
	hooks    []Hook
	mutation *PairingCodeMutation
}

// Where appends a list predicates to the PairingCodeUpdate builder.
func (_u *PairingCodeUpdate) Where(ps ...predicate.PairingCode) *PairingCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PairingCodeUpdate) SetUpdatedAt(v time.Time) *PairingCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *PairingCodeUpdate) SetCode(v string) *PairingCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *PairingCodeUpdate) SetNillableCode(v *string) *PairingCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDoctorID sets the "doctor_id" field.
func (_u *PairingCodeUpdate) SetDoctorID(v uuid.UUID) *PairingCodeUpdate {
	_u.mutation.SetDoctorID(v)
	return _u
}

// SetNillableDoctorID sets the "doctor_id" field if the given value is not nil.
func (_u *PairingCodeUpdate) SetNillableDoctorID(v *uuid.UUID) *PairingCodeUpdate {
	if v != nil {
		_u.SetDoctorID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PairingCodeUpdate) SetExpiresAt(v time.Time) *PairingCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PairingCodeUpdate) SetNillableExpiresAt(v *time.Time) *PairingCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *PairingCodeUpdate) SetConsumedAt(v time.Time) *PairingCodeUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *PairingCodeUpdate) SetNillableConsumedAt(v *time.Time) *PairingCodeUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *PairingCodeUpdate) ClearConsumedAt() *PairingCodeUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetConsumedByPatientID sets the "consumed_by_patient_id" field.
func (_u *PairingCodeUpdate) SetConsumedByPatientID(v uuid.UUID) *PairingCodeUpdate {
	_u.mutation.SetConsumedByPatientID(v)
	return _u
}

// SetNillableConsumedByPatientID sets the "consumed_by_patient_id" field if the given value is not nil.
func (_u *PairingCodeUpdate) SetNillableConsumedByPatientID(v *uuid.UUID) *PairingCodeUpdate {
	if v != nil {
		_u.SetConsumedByPatientID(*v)
	}
	return _u
}

// ClearConsumedByPatientID clears the value of the "consumed_by_patient_id" field.
func (_u *PairingCodeUpdate) ClearConsumedByPatientID() *PairingCodeUpdate {
	_u.mutation.ClearConsumedByPatientID()
	return _u
}

// SetDoctor sets the "doctor" edge to the Doctor entity.
func (_u *PairingCodeUpdate) SetDoctor(v *Doctor) *PairingCodeUpdate {
	return _u.SetDoctorID(v.ID)
}

// SetConsumedByPatient sets the "consumed_by_patient" edge to the Patient entity.
func (_u *PairingCodeUpdate) SetConsumedByPatient(v *Patient) *PairingCodeUpdate {
	return _u.SetConsumedByPatientID(v.ID)
}

// Mutation returns the PairingCodeMutation object of the builder.
func (_u *PairingCodeUpdate) Mutation() *PairingCodeMutation {
	return _u.mutation
}

// ClearDoctor clears the "doctor" edge to the Doctor entity.
func (_u *PairingCodeUpdate) ClearDoctor() *PairingCodeUpdate {
	_u.mutation.ClearDoctor()
	return _u
}

// ClearConsumedByPatient clears the "consumed_by_patient" edge to the Patient entity.
func (_u *PairingCodeUpdate) ClearConsumedByPatient() *PairingCodeUpdate {
	_u.mutation.ClearConsumedByPatient()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PairingCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PairingCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PairingCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PairingCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PairingCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pairingcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PairingCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := pairingcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "PairingCode.code": %w`, err)}
		}
	}
	if _u.mutation.DoctorCleared() && len(_u.mutation.DoctorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PairingCode.doctor"`)
	}
	return nil
}

func (_u *PairingCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pairingcode.Table, pairingcode.Columns, sqlgraph.NewFieldSpec(pairingcode.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pairingcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(pairingcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(pairingcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(pairingcode.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(pairingcode.FieldConsumedAt, field.TypeTime)
	}
	if _u.mutation.DoctorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pairingcode.DoctorTable,
			Columns: []string{pairingcode.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pairingcode.DoctorTable,
			Columns: []string{pairingcode.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConsumedByPatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pairingcode.ConsumedByPatientTable,
			Columns: []string{pairingcode.ConsumedByPatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsumedByPatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pairingcode.ConsumedByPatientTable,
			Columns: []string{pairingcode.ConsumedByPatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pairingcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PairingCodeUpdateOne is the builder for updating a single PairingCode entity.
type PairingCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PairingCodeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PairingCodeUpdateOne) SetUpdatedAt(v time.Time) *PairingCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *PairingCodeUpdateOne) SetCode(v string) *PairingCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *PairingCodeUpdateOne) SetNillableCode(v *string) *PairingCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDoctorID sets the "doctor_id" field.
func (_u *PairingCodeUpdateOne) SetDoctorID(v uuid.UUID) *PairingCodeUpdateOne {
	_u.mutation.SetDoctorID(v)
	return _u
}

// SetNillableDoctorID sets the "doctor_id" field if the given value is not nil.
func (_u *PairingCodeUpdateOne) SetNillableDoctorID(v *uuid.UUID) *PairingCodeUpdateOne {
	if v != nil {
		_u.SetDoctorID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PairingCodeUpdateOne) SetExpiresAt(v time.Time) *PairingCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PairingCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *PairingCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *PairingCodeUpdateOne) SetConsumedAt(v time.Time) *PairingCodeUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *PairingCodeUpdateOne) SetNillableConsumedAt(v *time.Time) *PairingCodeUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *PairingCodeUpdateOne) ClearConsumedAt() *PairingCodeUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetConsumedByPatientID sets the "consumed_by_patient_id" field.
func (_u *PairingCodeUpdateOne) SetConsumedByPatientID(v uuid.UUID) *PairingCodeUpdateOne {
	_u.mutation.SetConsumedByPatientID(v)
	return _u
}

// SetNillableConsumedByPatientID sets the "consumed_by_patient_id" field if the given value is not nil.
func (_u *PairingCodeUpdateOne) SetNillableConsumedByPatientID(v *uuid.UUID) *PairingCodeUpdateOne {
	if v != nil {
		_u.SetConsumedByPatientID(*v)
	}
	return _u
}

// ClearConsumedByPatientID clears the value of the "consumed_by_patient_id" field.
func (_u *PairingCodeUpdateOne) ClearConsumedByPatientID() *PairingCodeUpdateOne {
	_u.mutation.ClearConsumedByPatientID()
	return _u
}

// SetDoctor sets the "doctor" edge to the Doctor entity.
func (_u *PairingCodeUpdateOne) SetDoctor(v *Doctor) *PairingCodeUpdateOne {
	return _u.SetDoctorID(v.ID)
}

// SetConsumedByPatient sets the "consumed_by_patient" edge to the Patient entity.
func (_u *PairingCodeUpdateOne) SetConsumedByPatient(v *Patient) *PairingCodeUpdateOne {
	return _u.SetConsumedByPatientID(v.ID)
}

// Mutation returns the PairingCodeMutation object of the builder.
func (_u *PairingCodeUpdateOne) Mutation() *PairingCodeMutation {
	return _u.mutation
}

// ClearDoctor clears the "doctor" edge to the Doctor entity.
func (_u *PairingCodeUpdateOne) ClearDoctor() *PairingCodeUpdateOne {
	_u.mutation.ClearDoctor()
	return _u
}

// ClearConsumedByPatient clears the "consumed_by_patient" edge to the Patient entity.
func (_u *PairingCodeUpdateOne) ClearConsumedByPatient() *PairingCodeUpdateOne {
	_u.mutation.ClearConsumedByPatient()
	return _u
}

// Where appends a list predicates to the PairingCodeUpdate builder.
func (_u *PairingCodeUpdateOne) Where(ps ...predicate.PairingCode) *PairingCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PairingCodeUpdateOne) Select(field string, fields ...string) *PairingCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PairingCode entity.
func (_u *PairingCodeUpdateOne) Save(ctx context.Context) (*PairingCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PairingCodeUpdateOne) SaveX(ctx context.Context) *PairingCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PairingCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PairingCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PairingCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pairingcode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PairingCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := pairingcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "PairingCode.code": %w`, err)}
		}
	}
	if _u.mutation.DoctorCleared() && len(_u.mutation.DoctorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PairingCode.doctor"`)
	}
	return nil
}

func (_u *PairingCodeUpdateOne) sqlSave(ctx context.Context) (_node *PairingCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pairingcode.Table, pairingcode.Columns, sqlgraph.NewFieldSpec(pairingcode.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PairingCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pairingcode.FieldID)
		for _, f := range fields {
			if !pairingcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pairingcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pairingcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(pairingcode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(pairingcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(pairingcode.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(pairingcode.FieldConsumedAt, field.TypeTime)
	}
	if _u.mutation.DoctorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pairingcode.DoctorTable,
			Columns: []string{pairingcode.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pairingcode.DoctorTable,
			Columns: []string{pairingcode.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConsumedByPatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pairingcode.ConsumedByPatientTable,
			Columns: []string{pairingcode.ConsumedByPatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsumedByPatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pairingcode.ConsumedByPatientTable,
			Columns: []string{pairingcode.ConsumedByPatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PairingCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pairingcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
