// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/doctor"
	"backend/ent/practice"
	"backend/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PracticeUpdate is the builder for updating Practice entities.
type PracticeUpdate struct {
	config
	hooks    []Hook
	mutation *PracticeMutation
}

// Where appends a list predicates to the PracticeUpdate builder.
func (_u *PracticeUpdate) Where(ps ...predicate.Practice) *PracticeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PracticeUpdate) SetUpdatedAt(v time.Time) *PracticeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PracticeUpdate) SetName(v string) *PracticeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PracticeUpdate) SetNillableName(v *string) *PracticeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *PracticeUpdate) SetAddress(v string) *PracticeUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *PracticeUpdate) SetNillableAddress(v *string) *PracticeUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *PracticeUpdate) ClearAddress() *PracticeUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// AddDoctorIDs adds the "doctors" edge to the Doctor entity by IDs.
func (_u *PracticeUpdate) AddDoctorIDs(ids ...uuid.UUID) *PracticeUpdate {
	_u.mutation.AddDoctorIDs(ids...)
	return _u
}

// AddDoctors adds the "doctors" edges to the Doctor entity.
func (_u *PracticeUpdate) AddDoctors(v ...*Doctor) *PracticeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDoctorIDs(ids...)
}

// Mutation returns the PracticeMutation object of the builder.
func (_u *PracticeUpdate) Mutation() *PracticeMutation {
	return _u.mutation
}

// ClearDoctors clears all "doctors" edges to the Doctor entity.
func (_u *PracticeUpdate) ClearDoctors() *PracticeUpdate {
	_u.mutation.ClearDoctors()
	return _u
}

// RemoveDoctorIDs removes the "doctors" edge to Doctor entities by IDs.
func (_u *PracticeUpdate) RemoveDoctorIDs(ids ...uuid.UUID) *PracticeUpdate {
	_u.mutation.RemoveDoctorIDs(ids...)
	return _u
}

// RemoveDoctors removes "doctors" edges to Doctor entities.
func (_u *PracticeUpdate) RemoveDoctors(v ...*Doctor) *PracticeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDoctorIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PracticeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PracticeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PracticeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PracticeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PracticeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := practice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PracticeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := practice.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Practice.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PracticeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(practice.Table, practice.Columns, sqlgraph.NewFieldSpec(practice.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(practice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(practice.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(practice.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(practice.FieldAddress, field.TypeString)
	}
	if _u.mutation.DoctorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practice.DoctorsTable,
			Columns: []string{practice.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDoctorsIDs(); len(nodes) > 0 && !_u.mutation.DoctorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practice.DoctorsTable,
			Columns: []string{practice.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DoctorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practice.DoctorsTable,
			Columns: []string{practice.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{practice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PracticeUpdateOne is the builder for updating a single Practice entity.
type PracticeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PracticeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PracticeUpdateOne) SetUpdatedAt(v time.Time) *PracticeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PracticeUpdateOne) SetName(v string) *PracticeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PracticeUpdateOne) SetNillableName(v *string) *PracticeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *PracticeUpdateOne) SetAddress(v string) *PracticeUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *PracticeUpdateOne) SetNillableAddress(v *string) *PracticeUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *PracticeUpdateOne) ClearAddress() *PracticeUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// AddDoctorIDs adds the "doctors" edge to the Doctor entity by IDs.
func (_u *PracticeUpdateOne) AddDoctorIDs(ids ...uuid.UUID) *PracticeUpdateOne {
	_u.mutation.AddDoctorIDs(ids...)
	return _u
}

// AddDoctors adds the "doctors" edges to the Doctor entity.
func (_u *PracticeUpdateOne) AddDoctors(v ...*Doctor) *PracticeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDoctorIDs(ids...)
}

// Mutation returns the PracticeMutation object of the builder.
func (_u *PracticeUpdateOne) Mutation() *PracticeMutation {
	return _u.mutation
}

// ClearDoctors clears all "doctors" edges to the Doctor entity.
func (_u *PracticeUpdateOne) ClearDoctors() *PracticeUpdateOne {
	_u.mutation.ClearDoctors()
	return _u
}

// RemoveDoctorIDs removes the "doctors" edge to Doctor entities by IDs.
func (_u *PracticeUpdateOne) RemoveDoctorIDs(ids ...uuid.UUID) *PracticeUpdateOne {
	_u.mutation.RemoveDoctorIDs(ids...)
	return _u
}

// RemoveDoctors removes "doctors" edges to Doctor entities.
func (_u *PracticeUpdateOne) RemoveDoctors(v ...*Doctor) *PracticeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDoctorIDs(ids...)
}

// Where appends a list predicates to the PracticeUpdate builder.
func (_u *PracticeUpdateOne) Where(ps ...predicate.Practice) *PracticeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PracticeUpdateOne) Select(field string, fields ...string) *PracticeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Practice entity.
func (_u *PracticeUpdateOne) Save(ctx context.Context) (*Practice, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PracticeUpdateOne) SaveX(ctx context.Context) *Practice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PracticeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PracticeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PracticeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := practice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PracticeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := practice.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Practice.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PracticeUpdateOne) sqlSave(ctx context.Context) (_node *Practice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(practice.Table, practice.Columns, sqlgraph.NewFieldSpec(practice.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Practice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, practice.FieldID)
		for _, f := range fields {
			if !practice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != practice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(practice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(practice.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(practice.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(practice.FieldAddress, field.TypeString)
	}
	if _u.mutation.DoctorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practice.DoctorsTable,
			Columns: []string{practice.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDoctorsIDs(); len(nodes) > 0 && !_u.mutation.DoctorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practice.DoctorsTable,
			Columns: []string{practice.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DoctorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   practice.DoctorsTable,
			Columns: []string{practice.DoctorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(doctor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Practice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{practice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
