// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/doctor"
	"backend/ent/practice"
	"backend/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PracticeQuery is the builder for querying Practice entities.
type PracticeQuery struct {
	config
	ctx         *QueryContext
	order       []practice.OrderOption
	inters      []Interceptor
	predicates  []predicate.Practice
	withDoctors *DoctorQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PracticeQuery builder.
func (_q *PracticeQuery) Where(ps ...predicate.Practice) *PracticeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PracticeQuery) Limit(limit int) *PracticeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PracticeQuery) Offset(offset int) *PracticeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PracticeQuery) Unique(unique bool) *PracticeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PracticeQuery) Order(o ...practice.OrderOption) *PracticeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDoctors chains the current query on the "doctors" edge.
func (_q *PracticeQuery) QueryDoctors() *DoctorQuery {
	query := (&DoctorClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(practice.Table, practice.FieldID, selector),
			sqlgraph.To(doctor.Table, doctor.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, practice.DoctorsTable, practice.DoctorsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Practice entity from the query.
// Returns a *NotFoundError when no Practice was found.
func (_q *PracticeQuery) First(ctx context.Context) (*Practice, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{practice.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PracticeQuery) FirstX(ctx context.Context) *Practice {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Practice ID from the query.
// Returns a *NotFoundError when no Practice ID was found.
func (_q *PracticeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{practice.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PracticeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Practice entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Practice entity is found.
// Returns a *NotFoundError when no Practice entities are found.
func (_q *PracticeQuery) Only(ctx context.Context) (*Practice, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{practice.Label}
	default:
		return nil, &NotSingularError{practice.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PracticeQuery) OnlyX(ctx context.Context) *Practice {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Practice ID in the query.
// Returns a *NotSingularError when more than one Practice ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PracticeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{practice.Label}
	default:
		err = &NotSingularError{practice.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PracticeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Practices.
func (_q *PracticeQuery) All(ctx context.Context) ([]*Practice, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Practice, *PracticeQuery]()
	return withInterceptors[[]*Practice](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PracticeQuery) AllX(ctx context.Context) []*Practice {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Practice IDs.
func (_q *PracticeQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(practice.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PracticeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PracticeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PracticeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PracticeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PracticeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PracticeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PracticeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PracticeQuery) Clone() *PracticeQuery {
	if _q == nil {
		return nil
	}
	return &PracticeQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]practice.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.Practice{}, _q.predicates...),
		withDoctors: _q.withDoctors.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDoctors tells the query-builder to eager-load the nodes that are connected to
// the "doctors" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PracticeQuery) WithDoctors(opts ...func(*DoctorQuery)) *PracticeQuery {
	query := (&DoctorClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDoctors = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Practice.Query().
//		GroupBy(practice.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PracticeQuery) GroupBy(field string, fields ...string) *PracticeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PracticeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = practice.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Practice.Query().
//		Select(practice.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *PracticeQuery) Select(fields ...string) *PracticeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PracticeSelect{PracticeQuery: _q}
	sbuild.label = practice.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PracticeSelect configured with the given aggregations.
func (_q *PracticeQuery) Aggregate(fns ...AggregateFunc) *PracticeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PracticeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !practice.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PracticeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Practice, error) {
	var (
		nodes       = []*Practice{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withDoctors != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Practice).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Practice{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDoctors; query != nil {
		if err := _q.loadDoctors(ctx, query, nodes,
			func(n *Practice) { n.Edges.Doctors = []*Doctor{} },
			func(n *Practice, e *Doctor) { n.Edges.Doctors = append(n.Edges.Doctors, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PracticeQuery) loadDoctors(ctx context.Context, query *DoctorQuery, nodes []*Practice, init func(*Practice), assign func(*Practice, *Doctor)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Practice)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(doctor.FieldPracticeID)
	}
	query.Where(predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(practice.DoctorsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PracticeID
		if fk == nil {
			return fmt.Errorf(`foreign-key "practice_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "practice_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PracticeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PracticeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(practice.Table, practice.Columns, sqlgraph.NewFieldSpec(practice.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, practice.FieldID)
		for i := range fields {
			if fields[i] != practice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PracticeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(practice.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = practice.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PracticeGroupBy is the group-by builder for Practice entities.
type PracticeGroupBy struct {
	selector
	build *PracticeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PracticeGroupBy) Aggregate(fns ...AggregateFunc) *PracticeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PracticeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PracticeQuery, *PracticeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PracticeGroupBy) sqlScan(ctx context.Context, root *PracticeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PracticeSelect is the builder for selecting fields of Practice entities.
type PracticeSelect struct {
	*PracticeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PracticeSelect) Aggregate(fns ...AggregateFunc) *PracticeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PracticeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PracticeQuery, *PracticeSelect](ctx, _s.PracticeQuery, _s, _s.inters, v)
}

func (_s *PracticeSelect) sqlScan(ctx context.Context, root *PracticeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
