// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/analysisjob"
	"backend/ent/comment"
	"backend/ent/doctor"
	"backend/ent/doctorpatientlink"
	"backend/ent/entry"
	"backend/ent/entryshare"
	"backend/ent/patient"
	"backend/ent/practice"
	"backend/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	analysisjobMixin := schema.AnalysisJob{}.Mixin()
	analysisjobMixinFields0 := analysisjobMixin[0].Fields()
	_ = analysisjobMixinFields0
	analysisjobMixinFields1 := analysisjobMixin[1].Fields()
	_ = analysisjobMixinFields1
	analysisjobFields := schema.AnalysisJob{}.Fields()
	_ = analysisjobFields
	// analysisjobDescCreatedAt is the schema descriptor for created_at field.
	analysisjobDescCreatedAt := analysisjobMixinFields1[0].Descriptor()
	// analysisjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	analysisjob.DefaultCreatedAt = analysisjobDescCreatedAt.Default.(func() time.Time)
	// analysisjobDescUpdatedAt is the schema descriptor for updated_at field.
	analysisjobDescUpdatedAt := analysisjobMixinFields1[1].Descriptor()
	// analysisjob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	analysisjob.DefaultUpdatedAt = analysisjobDescUpdatedAt.Default.(func() time.Time)
	// analysisjob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	analysisjob.UpdateDefaultUpdatedAt = analysisjobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// analysisjobDescObjectKey is the schema descriptor for object_key field.
	analysisjobDescObjectKey := analysisjobFields[2].Descriptor()
	// analysisjob.ObjectKeyValidator is a validator for the "object_key" field. It is called by the builders before save.
	analysisjob.ObjectKeyValidator = analysisjobDescObjectKey.Validators[0].(func(string) error)
	// analysisjobDescKind is the schema descriptor for kind field.
	analysisjobDescKind := analysisjobFields[3].Descriptor()
	// analysisjob.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	analysisjob.KindValidator = analysisjobDescKind.Validators[0].(func(string) error)
	// analysisjobDescID is the schema descriptor for id field.
	analysisjobDescID := analysisjobMixinFields0[0].Descriptor()
	// analysisjob.DefaultID holds the default value on creation for the id field.
	analysisjob.DefaultID = analysisjobDescID.Default.(func() uuid.UUID)
	commentMixin := schema.Comment{}.Mixin()
	commentMixinFields0 := commentMixin[0].Fields()
	_ = commentMixinFields0
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescBody is the schema descriptor for body field.
	commentDescBody := commentFields[2].Descriptor()
	// comment.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	comment.BodyValidator = commentDescBody.Validators[0].(func(string) error)
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[3].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentMixinFields0[0].Descriptor()
	// comment.DefaultID holds the default value on creation for the id field.
	comment.DefaultID = commentDescID.Default.(func() uuid.UUID)
	doctorMixin := schema.Doctor{}.Mixin()
	doctorMixinFields0 := doctorMixin[0].Fields()
	_ = doctorMixinFields0
	doctorMixinFields1 := doctorMixin[1].Fields()
	_ = doctorMixinFields1
	doctorFields := schema.Doctor{}.Fields()
	_ = doctorFields
	// doctorDescCreatedAt is the schema descriptor for created_at field.
	doctorDescCreatedAt := doctorMixinFields1[0].Descriptor()
	// doctor.DefaultCreatedAt holds the default value on creation for the created_at field.
	doctor.DefaultCreatedAt = doctorDescCreatedAt.Default.(func() time.Time)
	// doctorDescUpdatedAt is the schema descriptor for updated_at field.
	doctorDescUpdatedAt := doctorMixinFields1[1].Descriptor()
	// doctor.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	doctor.DefaultUpdatedAt = doctorDescUpdatedAt.Default.(func() time.Time)
	// doctor.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	doctor.UpdateDefaultUpdatedAt = doctorDescUpdatedAt.UpdateDefault.(func() time.Time)
	// doctorDescEmail is the schema descriptor for email field.
	doctorDescEmail := doctorFields[0].Descriptor()
	// doctor.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	doctor.EmailValidator = doctorDescEmail.Validators[0].(func(string) error)
	// doctorDescDisplayName is the schema descriptor for display_name field.
	doctorDescDisplayName := doctorFields[1].Descriptor()
	// doctor.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	doctor.DisplayNameValidator = doctorDescDisplayName.Validators[0].(func(string) error)
	// doctorDescPasswordHash is the schema descriptor for password_hash field.
	doctorDescPasswordHash := doctorFields[2].Descriptor()
	// doctor.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	doctor.PasswordHashValidator = doctorDescPasswordHash.Validators[0].(func(string) error)
	// doctorDescID is the schema descriptor for id field.
	doctorDescID := doctorMixinFields0[0].Descriptor()
	// doctor.DefaultID holds the default value on creation for the id field.
	doctor.DefaultID = doctorDescID.Default.(func() uuid.UUID)
	doctorpatientlinkMixin := schema.DoctorPatientLink{}.Mixin()
	doctorpatientlinkMixinFields0 := doctorpatientlinkMixin[0].Fields()
	_ = doctorpatientlinkMixinFields0
	doctorpatientlinkMixinFields1 := doctorpatientlinkMixin[1].Fields()
	_ = doctorpatientlinkMixinFields1
	doctorpatientlinkFields := schema.DoctorPatientLink{}.Fields()
	_ = doctorpatientlinkFields
	// doctorpatientlinkDescCreatedAt is the schema descriptor for created_at field.
	doctorpatientlinkDescCreatedAt := doctorpatientlinkMixinFields1[0].Descriptor()
	// doctorpatientlink.DefaultCreatedAt holds the default value on creation for the created_at field.
	doctorpatientlink.DefaultCreatedAt = doctorpatientlinkDescCreatedAt.Default.(func() time.Time)
	// doctorpatientlinkDescUpdatedAt is the schema descriptor for updated_at field.
	doctorpatientlinkDescUpdatedAt := doctorpatientlinkMixinFields1[1].Descriptor()
	// doctorpatientlink.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	doctorpatientlink.DefaultUpdatedAt = doctorpatientlinkDescUpdatedAt.Default.(func() time.Time)
	// doctorpatientlink.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	doctorpatientlink.UpdateDefaultUpdatedAt = doctorpatientlinkDescUpdatedAt.UpdateDefault.(func() time.Time)
	// doctorpatientlinkDescRequestedAt is the schema descriptor for requested_at field.
	doctorpatientlinkDescRequestedAt := doctorpatientlinkFields[3].Descriptor()
	// doctorpatientlink.DefaultRequestedAt holds the default value on creation for the requested_at field.
	doctorpatientlink.DefaultRequestedAt = doctorpatientlinkDescRequestedAt.Default.(func() time.Time)
	// doctorpatientlinkDescID is the schema descriptor for id field.
	doctorpatientlinkDescID := doctorpatientlinkMixinFields0[0].Descriptor()
	// doctorpatientlink.DefaultID holds the default value on creation for the id field.
	doctorpatientlink.DefaultID = doctorpatientlinkDescID.Default.(func() uuid.UUID)
	entryMixin := schema.Entry{}.Mixin()
	entryMixinFields0 := entryMixin[0].Fields()
	_ = entryMixinFields0
	entryMixinFields1 := entryMixin[1].Fields()
	_ = entryMixinFields1
	entryFields := schema.Entry{}.Fields()
	_ = entryFields
	// entryDescCreatedAt is the schema descriptor for created_at field.
	entryDescCreatedAt := entryMixinFields1[0].Descriptor()
	// entry.DefaultCreatedAt holds the default value on creation for the created_at field.
	entry.DefaultCreatedAt = entryDescCreatedAt.Default.(func() time.Time)
	// entryDescUpdatedAt is the schema descriptor for updated_at field.
	entryDescUpdatedAt := entryMixinFields1[1].Descriptor()
	// entry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entry.DefaultUpdatedAt = entryDescUpdatedAt.Default.(func() time.Time)
	// entry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entry.UpdateDefaultUpdatedAt = entryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entryDescHappenedAt is the schema descriptor for happened_at field.
	entryDescHappenedAt := entryFields[1].Descriptor()
	// entry.DefaultHappenedAt holds the default value on creation for the happened_at field.
	entry.DefaultHappenedAt = entryDescHappenedAt.Default.(func() time.Time)
	// entryDescID is the schema descriptor for id field.
	entryDescID := entryMixinFields0[0].Descriptor()
	// entry.DefaultID holds the default value on creation for the id field.
	entry.DefaultID = entryDescID.Default.(func() uuid.UUID)
	entryshareMixin := schema.EntryShare{}.Mixin()
	entryshareMixinFields0 := entryshareMixin[0].Fields()
	_ = entryshareMixinFields0
	entryshareMixinFields1 := entryshareMixin[1].Fields()
	_ = entryshareMixinFields1
	entryshareFields := schema.EntryShare{}.Fields()
	_ = entryshareFields
	// entryshareDescCreatedAt is the schema descriptor for created_at field.
	entryshareDescCreatedAt := entryshareMixinFields1[0].Descriptor()
	// entryshare.DefaultCreatedAt holds the default value on creation for the created_at field.
	entryshare.DefaultCreatedAt = entryshareDescCreatedAt.Default.(func() time.Time)
	// entryshareDescUpdatedAt is the schema descriptor for updated_at field.
	entryshareDescUpdatedAt := entryshareMixinFields1[1].Descriptor()
	// entryshare.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	entryshare.DefaultUpdatedAt = entryshareDescUpdatedAt.Default.(func() time.Time)
	// entryshare.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	entryshare.UpdateDefaultUpdatedAt = entryshareDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entryshareDescSharedAt is the schema descriptor for shared_at field.
	entryshareDescSharedAt := entryshareFields[3].Descriptor()
	// entryshare.DefaultSharedAt holds the default value on creation for the shared_at field.
	entryshare.DefaultSharedAt = entryshareDescSharedAt.Default.(func() time.Time)
	// entryshareDescID is the schema descriptor for id field.
	entryshareDescID := entryshareMixinFields0[0].Descriptor()
	// entryshare.DefaultID holds the default value on creation for the id field.
	entryshare.DefaultID = entryshareDescID.Default.(func() uuid.UUID)
	patientMixin := schema.Patient{}.Mixin()
	patientMixinFields0 := patientMixin[0].Fields()
	_ = patientMixinFields0
	patientMixinFields1 := patientMixin[1].Fields()
	_ = patientMixinFields1
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescCreatedAt is the schema descriptor for created_at field.
	patientDescCreatedAt := patientMixinFields1[0].Descriptor()
	// patient.DefaultCreatedAt holds the default value on creation for the created_at field.
	patient.DefaultCreatedAt = patientDescCreatedAt.Default.(func() time.Time)
	// patientDescUpdatedAt is the schema descriptor for updated_at field.
	patientDescUpdatedAt := patientMixinFields1[1].Descriptor()
	// patient.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	patient.DefaultUpdatedAt = patientDescUpdatedAt.Default.(func() time.Time)
	// patient.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	patient.UpdateDefaultUpdatedAt = patientDescUpdatedAt.UpdateDefault.(func() time.Time)
	// patientDescDisplayName is the schema descriptor for display_name field.
	patientDescDisplayName := patientFields[0].Descriptor()
	// patient.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	patient.DisplayNameValidator = patientDescDisplayName.Validators[0].(func(string) error)
	// patientDescLastEntryAt is the schema descriptor for last_entry_at field.
	patientDescLastEntryAt := patientFields[6].Descriptor()
	// patient.UpdateDefaultLastEntryAt holds the default value on update for the last_entry_at field.
	patient.UpdateDefaultLastEntryAt = patientDescLastEntryAt.UpdateDefault.(func() time.Time)
	// patientDescID is the schema descriptor for id field.
	patientDescID := patientMixinFields0[0].Descriptor()
	// patient.DefaultID holds the default value on creation for the id field.
	patient.DefaultID = patientDescID.Default.(func() uuid.UUID)
	practiceMixin := schema.Practice{}.Mixin()
	practiceMixinFields0 := practiceMixin[0].Fields()
	_ = practiceMixinFields0
	practiceMixinFields1 := practiceMixin[1].Fields()
	_ = practiceMixinFields1
	practiceFields := schema.Practice{}.Fields()
	_ = practiceFields
	// practiceDescCreatedAt is the schema descriptor for created_at field.
	practiceDescCreatedAt := practiceMixinFields1[0].Descriptor()
	// practice.DefaultCreatedAt holds the default value on creation for the created_at field.
	practice.DefaultCreatedAt = practiceDescCreatedAt.Default.(func() time.Time)
	// practiceDescUpdatedAt is the schema descriptor for updated_at field.
	practiceDescUpdatedAt := practiceMixinFields1[1].Descriptor()
	// practice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	practice.DefaultUpdatedAt = practiceDescUpdatedAt.Default.(func() time.Time)
	// practice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	practice.UpdateDefaultUpdatedAt = practiceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// practiceDescName is the schema descriptor for name field.
	practiceDescName := practiceFields[0].Descriptor()
	// practice.NameValidator is a validator for the "name" field. It is called by the builders before save.
	practice.NameValidator = practiceDescName.Validators[0].(func(string) error)
	// practiceDescID is the schema descriptor for id field.
	practiceDescID := practiceMixinFields0[0].Descriptor()
	// practice.DefaultID holds the default value on creation for the id field.
	practice.DefaultID = practiceDescID.Default.(func() uuid.UUID)
}
