// Code generated by ent, DO NOT EDIT.

package entry

import (
	"backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldUpdatedAt, v))
}

// PatientID applies equality check predicate on the "patient_id" field. It's identical to PatientIDEQ.
func PatientID(v uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldPatientID, v))
}

// HappenedAt applies equality check predicate on the "happened_at" field. It's identical to HappenedAtEQ.
func HappenedAt(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldHappenedAt, v))
}

// Situation applies equality check predicate on the "situation" field. It's identical to SituationEQ.
func Situation(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldSituation, v))
}

// StutterFrequency applies equality check predicate on the "stutter_frequency" field. It's identical to StutterFrequencyEQ.
func StutterFrequency(v int) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldStutterFrequency, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldUpdatedAt, v))
}

// PatientIDEQ applies the EQ predicate on the "patient_id" field.
func PatientIDEQ(v uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldPatientID, v))
}

// PatientIDNEQ applies the NEQ predicate on the "patient_id" field.
func PatientIDNEQ(v uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldPatientID, v))
}

// PatientIDIn applies the In predicate on the "patient_id" field.
func PatientIDIn(vs ...uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldPatientID, vs...))
}

// PatientIDNotIn applies the NotIn predicate on the "patient_id" field.
func PatientIDNotIn(vs ...uuid.UUID) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldPatientID, vs...))
}

// HappenedAtEQ applies the EQ predicate on the "happened_at" field.
func HappenedAtEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldHappenedAt, v))
}

// HappenedAtNEQ applies the NEQ predicate on the "happened_at" field.
func HappenedAtNEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldHappenedAt, v))
}

// HappenedAtIn applies the In predicate on the "happened_at" field.
func HappenedAtIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldHappenedAt, vs...))
}

// HappenedAtNotIn applies the NotIn predicate on the "happened_at" field.
func HappenedAtNotIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldHappenedAt, vs...))
}

// HappenedAtGT applies the GT predicate on the "happened_at" field.
func HappenedAtGT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldHappenedAt, v))
}

// HappenedAtGTE applies the GTE predicate on the "happened_at" field.
func HappenedAtGTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldHappenedAt, v))
}

// HappenedAtLT applies the LT predicate on the "happened_at" field.
func HappenedAtLT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldHappenedAt, v))
}

// HappenedAtLTE applies the LTE predicate on the "happened_at" field.
func HappenedAtLTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldHappenedAt, v))
}

// SituationEQ applies the EQ predicate on the "situation" field.
func SituationEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldSituation, v))
}

// SituationNEQ applies the NEQ predicate on the "situation" field.
func SituationNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldSituation, v))
}

// SituationIn applies the In predicate on the "situation" field.
func SituationIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldSituation, vs...))
}

// SituationNotIn applies the NotIn predicate on the "situation" field.
func SituationNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldSituation, vs...))
}

// SituationGT applies the GT predicate on the "situation" field.
func SituationGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldSituation, v))
}

// SituationGTE applies the GTE predicate on the "situation" field.
func SituationGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldSituation, v))
}

// SituationLT applies the LT predicate on the "situation" field.
func SituationLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldSituation, v))
}

// SituationLTE applies the LTE predicate on the "situation" field.
func SituationLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldSituation, v))
}

// SituationContains applies the Contains predicate on the "situation" field.
func SituationContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldSituation, v))
}

// SituationHasPrefix applies the HasPrefix predicate on the "situation" field.
func SituationHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldSituation, v))
}

// SituationHasSuffix applies the HasSuffix predicate on the "situation" field.
func SituationHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldSituation, v))
}

// SituationIsNil applies the IsNil predicate on the "situation" field.
func SituationIsNil() predicate.Entry {
	return predicate.Entry(sql.FieldIsNull(FieldSituation))
}

// SituationNotNil applies the NotNil predicate on the "situation" field.
func SituationNotNil() predicate.Entry {
	return predicate.Entry(sql.FieldNotNull(FieldSituation))
}

// SituationEqualFold applies the EqualFold predicate on the "situation" field.
func SituationEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldSituation, v))
}

// SituationContainsFold applies the ContainsFold predicate on the "situation" field.
func SituationContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldSituation, v))
}

// EmotionsIsNil applies the IsNil predicate on the "emotions" field.
func EmotionsIsNil() predicate.Entry {
	return predicate.Entry(sql.FieldIsNull(FieldEmotions))
}

// EmotionsNotNil applies the NotNil predicate on the "emotions" field.
func EmotionsNotNil() predicate.Entry {
	return predicate.Entry(sql.FieldNotNull(FieldEmotions))
}

// TriggersIsNil applies the IsNil predicate on the "triggers" field.
func TriggersIsNil() predicate.Entry {
	return predicate.Entry(sql.FieldIsNull(FieldTriggers))
}

// TriggersNotNil applies the NotNil predicate on the "triggers" field.
func TriggersNotNil() predicate.Entry {
	return predicate.Entry(sql.FieldNotNull(FieldTriggers))
}

// TechniquesIsNil applies the IsNil predicate on the "techniques" field.
func TechniquesIsNil() predicate.Entry {
	return predicate.Entry(sql.FieldIsNull(FieldTechniques))
}

// TechniquesNotNil applies the NotNil predicate on the "techniques" field.
func TechniquesNotNil() predicate.Entry {
	return predicate.Entry(sql.FieldNotNull(FieldTechniques))
}

// StutterFrequencyEQ applies the EQ predicate on the "stutter_frequency" field.
func StutterFrequencyEQ(v int) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldStutterFrequency, v))
}

// StutterFrequencyNEQ applies the NEQ predicate on the "stutter_frequency" field.
func StutterFrequencyNEQ(v int) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldStutterFrequency, v))
}

// StutterFrequencyIn applies the In predicate on the "stutter_frequency" field.
func StutterFrequencyIn(vs ...int) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldStutterFrequency, vs...))
}

// StutterFrequencyNotIn applies the NotIn predicate on the "stutter_frequency" field.
func StutterFrequencyNotIn(vs ...int) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldStutterFrequency, vs...))
}

// StutterFrequencyGT applies the GT predicate on the "stutter_frequency" field.
func StutterFrequencyGT(v int) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldStutterFrequency, v))
}

// StutterFrequencyGTE applies the GTE predicate on the "stutter_frequency" field.
func StutterFrequencyGTE(v int) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldStutterFrequency, v))
}

// StutterFrequencyLT applies the LT predicate on the "stutter_frequency" field.
func StutterFrequencyLT(v int) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldStutterFrequency, v))
}

// StutterFrequencyLTE applies the LTE predicate on the "stutter_frequency" field.
func StutterFrequencyLTE(v int) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldStutterFrequency, v))
}

// StutterFrequencyIsNil applies the IsNil predicate on the "stutter_frequency" field.
func StutterFrequencyIsNil() predicate.Entry {
	return predicate.Entry(sql.FieldIsNull(FieldStutterFrequency))
}

// StutterFrequencyNotNil applies the NotNil predicate on the "stutter_frequency" field.
func StutterFrequencyNotNil() predicate.Entry {
	return predicate.Entry(sql.FieldNotNull(FieldStutterFrequency))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Entry {
	return predicate.Entry(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Entry {
	return predicate.Entry(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldNotes, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Entry {
	return predicate.Entry(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Entry {
	return predicate.Entry(sql.FieldNotNull(FieldTags))
}

// HasPatient applies the HasEdge predicate on the "patient" edge.
func HasPatient() predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PatientTable, PatientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPatientWith applies the HasEdge predicate on the "patient" edge with a given conditions (other predicates).
func HasPatientWith(preds ...predicate.Patient) predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := newPatientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasShares applies the HasEdge predicate on the "shares" edge.
func HasShares() predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SharesTable, SharesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSharesWith applies the HasEdge predicate on the "shares" edge with a given conditions (other predicates).
func HasSharesWith(preds ...predicate.EntryShare) predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := newSharesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasComments applies the HasEdge predicate on the "comments" edge.
func HasComments() predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentsWith applies the HasEdge predicate on the "comments" edge with a given conditions (other predicates).
func HasCommentsWith(preds ...predicate.Comment) predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := newCommentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnalysisJobs applies the HasEdge predicate on the "analysis_jobs" edge.
func HasAnalysisJobs() predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AnalysisJobsTable, AnalysisJobsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnalysisJobsWith applies the HasEdge predicate on the "analysis_jobs" edge with a given conditions (other predicates).
func HasAnalysisJobsWith(preds ...predicate.AnalysisJob) predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := newAnalysisJobsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Entry) predicate.Entry {
	return predicate.Entry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Entry) predicate.Entry {
	return predicate.Entry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Entry) predicate.Entry {
	return predicate.Entry(sql.NotPredicates(p))
}
