// Code generated by ent, DO NOT EDIT.

package pairingcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the pairingcode type in the database.
	Label = "pairing_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldDoctorID holds the string denoting the doctor_id field in the database.
	FieldDoctorID = "doctor_id"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldConsumedAt holds the string denoting the consumed_at field in the database.
	FieldConsumedAt = "consumed_at"
	// FieldConsumedByPatientID holds the string denoting the consumed_by_patient_id field in the database.
	FieldConsumedByPatientID = "consumed_by_patient_id"
	// EdgeDoctor holds the string denoting the doctor edge name in mutations.
	EdgeDoctor = "doctor"
	// EdgeConsumedByPatient holds the string denoting the consumed_by_patient edge name in mutations.
	EdgeConsumedByPatient = "consumed_by_patient"
	// Table holds the table name of the pairingcode in the database.
	Table = "pairing_codes"
	// DoctorTable is the table that holds the doctor relation/edge.
	DoctorTable = "pairing_codes"
	// DoctorInverseTable is the table name for the Doctor entity.
	// It exists in this package in order to avoid circular dependency with the "doctor" package.
	DoctorInverseTable = "doctors"
	// DoctorColumn is the table column denoting the doctor relation/edge.
	DoctorColumn = "doctor_id"
	// ConsumedByPatientTable is the table that holds the consumed_by_patient relation/edge.
	ConsumedByPatientTable = "pairing_codes"
	// ConsumedByPatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	ConsumedByPatientInverseTable = "patients"
	// ConsumedByPatientColumn is the table column denoting the consumed_by_patient relation/edge.
	ConsumedByPatientColumn = "consumed_by_patient_id"
)

// Columns holds all SQL columns for pairingcode fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCode,
	FieldDoctorID,
	FieldExpiresAt,
	FieldConsumedAt,
	FieldConsumedByPatientID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PairingCode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByDoctorID orders the results by the doctor_id field.
func ByDoctorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDoctorID, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByConsumedAt orders the results by the consumed_at field.
func ByConsumedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumedAt, opts...).ToFunc()
}

// ByConsumedByPatientID orders the results by the consumed_by_patient_id field.
func ByConsumedByPatientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsumedByPatientID, opts...).ToFunc()
}

// ByDoctorField orders the results by doctor field.
func ByDoctorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDoctorStep(), sql.OrderByField(field, opts...))
	}
}

// ByConsumedByPatientField orders the results by consumed_by_patient field.
func ByConsumedByPatientField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConsumedByPatientStep(), sql.OrderByField(field, opts...))
	}
}
func newDoctorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DoctorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DoctorTable, DoctorColumn),
	)
}
func newConsumedByPatientStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConsumedByPatientInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConsumedByPatientTable, ConsumedByPatientColumn),
	)
}
