// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AnalysisJob is the predicate function for analysisjob builders.
type AnalysisJob func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// DoctorPatientLink is the predicate function for doctorpatientlink builders.
type DoctorPatientLink func(*sql.Selector)

// Entry is the predicate function for entry builders.
type Entry func(*sql.Selector)

// EntryShare is the predicate function for entryshare builders.
type EntryShare func(*sql.Selector)

// PairingCode is the predicate function for pairingcode builders.
type PairingCode func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Practice is the predicate function for practice builders.
type Practice func(*sql.Selector)
