apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/apps/overlays/staging
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: infrastructure-staging
  sourceRef:
    kind: GitRepository
    name: flux-system
