apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/infrastructure/overlays/staging
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
