// Code generated by ent, DO NOT EDIT.

package analysisjob

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the analysisjob type in the database.
	Label = "analysis_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPatientID holds the string denoting the patient_id field in the database.
	FieldPatientID = "patient_id"
	// FieldCreatedByDoctorID holds the string denoting the created_by_doctor_id field in the database.
	FieldCreatedByDoctorID = "created_by_doctor_id"
	// FieldObjectKey holds the string denoting the object_key field in the database.
	FieldObjectKey = "object_key"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldMetrics holds the string denoting the metrics field in the database.
	FieldMetrics = "metrics"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldEntryID holds the string denoting the entry_id field in the database.
	FieldEntryID = "entry_id"
	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"
	// EdgeCreatedByDoctor holds the string denoting the created_by_doctor edge name in mutations.
	EdgeCreatedByDoctor = "created_by_doctor"
	// EdgeEntry holds the string denoting the entry edge name in mutations.
	EdgeEntry = "entry"
	// Table holds the table name of the analysisjob in the database.
	Table = "analysis_jobs"
	// PatientTable is the table that holds the patient relation/edge.
	PatientTable = "analysis_jobs"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "patient_id"
	// CreatedByDoctorTable is the table that holds the created_by_doctor relation/edge.
	CreatedByDoctorTable = "analysis_jobs"
	// CreatedByDoctorInverseTable is the table name for the Doctor entity.
	// It exists in this package in order to avoid circular dependency with the "doctor" package.
	CreatedByDoctorInverseTable = "doctors"
	// CreatedByDoctorColumn is the table column denoting the created_by_doctor relation/edge.
	CreatedByDoctorColumn = "created_by_doctor_id"
	// EntryTable is the table that holds the entry relation/edge.
	EntryTable = "analysis_jobs"
	// EntryInverseTable is the table name for the Entry entity.
	// It exists in this package in order to avoid circular dependency with the "entry" package.
	EntryInverseTable = "entries"
	// EntryColumn is the table column denoting the entry relation/edge.
	EntryColumn = "entry_id"
)

// Columns holds all SQL columns for analysisjob fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPatientID,
	FieldCreatedByDoctorID,
	FieldObjectKey,
	FieldKind,
	FieldStatus,
	FieldProgress,
	FieldResult,
	FieldMetrics,
	FieldErrorMessage,
	FieldStartedAt,
	FieldFinishedAt,
	FieldEntryID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ObjectKeyValidator is a validator for the "object_key" field. It is called by the builders before save.
	ObjectKeyValidator func(string) error
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusQueued is the default value of the Status enum.
const DefaultStatus = StatusQueued

// Status values.
const (
	StatusQueued  Status = "Queued"
	StatusRunning Status = "Running"
	StatusDone    Status = "Done"
	StatusFailed  Status = "Failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusQueued, StatusRunning, StatusDone, StatusFailed:
		return nil
	default:
		return fmt.Errorf("analysisjob: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AnalysisJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPatientID orders the results by the patient_id field.
func ByPatientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPatientID, opts...).ToFunc()
}

// ByCreatedByDoctorID orders the results by the created_by_doctor_id field.
func ByCreatedByDoctorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByDoctorID, opts...).ToFunc()
}

// ByObjectKey orders the results by the object_key field.
func ByObjectKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjectKey, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByEntryID orders the results by the entry_id field.
func ByEntryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryID, opts...).ToFunc()
}

// ByPatientField orders the results by patient field.
func ByPatientField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPatientStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatedByDoctorField orders the results by created_by_doctor field.
func ByCreatedByDoctorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedByDoctorStep(), sql.OrderByField(field, opts...))
	}
}

// ByEntryField orders the results by entry field.
func ByEntryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntryStep(), sql.OrderByField(field, opts...))
	}
}
func newPatientStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PatientInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PatientTable, PatientColumn),
	)
}
func newCreatedByDoctorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedByDoctorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatedByDoctorTable, CreatedByDoctorColumn),
	)
}
func newEntryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntryTable, EntryColumn),
	)
}
